
BlockImage = "image::" path:(Path) attributes:(InlineAttributes) AnySpaces  {
    return compose(c, asciidoc.NewBlockImage(path.(asciidoc.Elements)), setAttributes[*asciidoc.BlockImage](attributes))
}

InlineImage = InlineImageDelimiter !":" path:(Path) attributes:(InlineAttributes)  {
    return compose(c, asciidoc.NewInlineImage(path.(asciidoc.Elements)), setAttributes[*asciidoc.InlineImage](attributes))
}

InlineImageDelimiter = "image:"