
URLScheme = ("https://" / "http://" / "ftp://" / "irc://" / "mailto:") {
    debugPosition(c, "matched url scheme\n")
    return string(c.text), nil
}

URL = scheme:(URLScheme)? path:(Path) {
    debugPosition(c, "matched url\n")
    s, _ := scheme.(string)
    return compose(c, asciidoc.NewURL(s, path))
}

FullURL = !"[" scheme:(URLScheme) path:(Path) {
    debugPosition(c, "matched full url\n")
    return compose(c, asciidoc.NewURL(scheme.(string), path))
}

