Range <- from:Limit __ "to"i __ to:Limit {
	debug("found range %s\n", string(c.text))
	return &RangeConstraint  {
		Minimum:from.(Limit),
		Maximum:to.(Limit),
	}, nil
}

Min <- "min"i __ limit:Limit {
	debug("found min limit %s\n", string(c.text))
	return &MinConstraint{Minimum:limit.(Limit)}, nil
}

Max <- "max"i __ limit:Limit (_ "chars"i)? {
	debug("found max limit %s\n", string(c.text))
	return &MaxConstraint{Maximum:limit.(Limit)}, nil
}