// Code generated by pigeon; DO NOT EDIT.

package conformance

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/shopspring/decimal"
)

func debug(format string, a ...any) (n int, err error) {
	return
	//return fmt.Fprintf(os.Stdout, format, a...)
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Input",
			pos:  position{line: 19, col: 1, offset: 259},
			expr: &actionExpr{
				pos: position{line: 19, col: 10, offset: 268},
				run: (*parser).callonInput1,
				expr: &seqExpr{
					pos: position{line: 19, col: 10, offset: 268},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 19, col: 10, offset: 268},
							label: "conf",
							expr: &oneOrMoreExpr{
								pos: position{line: 19, col: 15, offset: 273},
								expr: &ruleRefExpr{
									pos:    position{line: 19, col: 15, offset: 273},
									offset: 3,
								},
							},
						},
						&ruleRefExpr{
							pos:    position{line: 19, col: 28, offset: 286},
							offset: 47,
						},
					},
				},
			},
		},
		{
			name: "ConformanceSeparator",
			pos:  position{line: 30, col: 1, offset: 458},
			expr: &choiceExpr{
				pos: position{line: 30, col: 25, offset: 482},
				alternatives: []any{
					&seqExpr{
						pos: position{line: 30, col: 26, offset: 483},
						exprs: []any{
							&ruleRefExpr{
								pos:    position{line: 30, col: 26, offset: 483},
								offset: 45,
							},
							&ruleRefExpr{
								pos:    position{line: 30, col: 28, offset: 485},
								offset: 46,
							},
							&ruleRefExpr{
								pos:    position{line: 30, col: 34, offset: 491},
								offset: 45,
							},
						},
					},
					&andExpr{
						pos: position{line: 30, col: 39, offset: 496},
						expr: &ruleRefExpr{
							pos:    position{line: 30, col: 40, offset: 497},
							offset: 47,
						},
					},
				},
			},
		},
		{
			name: "Expression",
			pos:  position{line: 32, col: 1, offset: 502},
			expr: &ruleRefExpr{
				pos:    position{line: 32, col: 16, offset: 517},
				offset: 4,
			},
		},
		{
			name: "Conformance",
			pos:  position{line: 34, col: 1, offset: 529},
			expr: &choiceExpr{
				pos: position{line: 34, col: 17, offset: 545},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 34, col: 17, offset: 545},
						run: (*parser).callonConformance2,
						expr: &seqExpr{
							pos: position{line: 34, col: 17, offset: 545},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 34, col: 17, offset: 545},
									val:        "[",
									ignoreCase: false,
									want:       "\"[\"",
								},
								&labeledExpr{
									pos:   position{line: 34, col: 21, offset: 549},
									label: "i",
									expr: &ruleRefExpr{
										pos:    position{line: 34, col: 23, offset: 551},
										offset: 2,
									},
								},
								&litMatcher{
									pos:        position{line: 34, col: 34, offset: 562},
									val:        "]",
									ignoreCase: false,
									want:       "\"]\"",
								},
								&labeledExpr{
									pos:   position{line: 34, col: 38, offset: 566},
									label: "choice",
									expr: &zeroOrOneExpr{
										pos: position{line: 34, col: 45, offset: 573},
										expr: &ruleRefExpr{
											pos:    position{line: 34, col: 45, offset: 573},
											offset: 39,
										},
									},
								},
								&ruleRefExpr{
									pos:    position{line: 34, col: 53, offset: 581},
									offset: 1,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 41, col: 6, offset: 756},
						run: (*parser).callonConformance12,
						expr: &seqExpr{
							pos: position{line: 41, col: 6, offset: 756},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 41, col: 6, offset: 756},
									val:        "M",
									ignoreCase: false,
									want:       "\"M\"",
								},
								&ruleRefExpr{
									pos:    position{line: 41, col: 11, offset: 761},
									offset: 1,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 43, col: 5, offset: 817},
						run: (*parser).callonConformance16,
						expr: &seqExpr{
							pos: position{line: 43, col: 5, offset: 817},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 43, col: 5, offset: 817},
									val:        "O",
									ignoreCase: false,
									want:       "\"O\"",
								},
								&labeledExpr{
									pos:   position{line: 43, col: 9, offset: 821},
									label: "choice",
									expr: &zeroOrOneExpr{
										pos: position{line: 43, col: 16, offset: 828},
										expr: &ruleRefExpr{
											pos:    position{line: 43, col: 16, offset: 828},
											offset: 39,
										},
									},
								},
								&ruleRefExpr{
									pos:    position{line: 43, col: 25, offset: 837},
									offset: 1,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 49, col: 5, offset: 968},
						run: (*parser).callonConformance23,
						expr: &seqExpr{
							pos: position{line: 49, col: 5, offset: 968},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 49, col: 5, offset: 968},
									val:        "P",
									ignoreCase: false,
									want:       "\"P\"",
								},
								&ruleRefExpr{
									pos:    position{line: 49, col: 10, offset: 973},
									offset: 1,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 51, col: 5, offset: 1035},
						run: (*parser).callonConformance27,
						expr: &seqExpr{
							pos: position{line: 51, col: 5, offset: 1035},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 51, col: 5, offset: 1035},
									val:        "D",
									ignoreCase: false,
									want:       "\"D\"",
								},
								&ruleRefExpr{
									pos:    position{line: 51, col: 10, offset: 1040},
									offset: 1,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 53, col: 5, offset: 1097},
						run: (*parser).callonConformance31,
						expr: &seqExpr{
							pos: position{line: 53, col: 5, offset: 1097},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 53, col: 5, offset: 1097},
									val:        "X",
									ignoreCase: false,
									want:       "\"X\"",
								},
								&ruleRefExpr{
									pos:    position{line: 53, col: 10, offset: 1102},
									offset: 1,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 55, col: 5, offset: 1159},
						run: (*parser).callonConformance35,
						expr: &seqExpr{
							pos: position{line: 55, col: 5, offset: 1159},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 55, col: 5, offset: 1159},
									val:        "desc",
									ignoreCase: false,
									want:       "\"desc\"",
								},
								&ruleRefExpr{
									pos:    position{line: 55, col: 13, offset: 1167},
									offset: 1,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 57, col: 5, offset: 1225},
						run: (*parser).callonConformance39,
						expr: &seqExpr{
							pos: position{line: 57, col: 5, offset: 1225},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 57, col: 5, offset: 1225},
									label: "eq",
									expr: &ruleRefExpr{
										pos:    position{line: 57, col: 8, offset: 1228},
										offset: 20,
									},
								},
								&ruleRefExpr{
									pos:    position{line: 57, col: 19, offset: 1239},
									offset: 1,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 60, col: 5, offset: 1336},
						run: (*parser).callonConformance44,
						expr: &seqExpr{
							pos: position{line: 60, col: 5, offset: 1336},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 60, col: 5, offset: 1336},
									label: "eq",
									expr: &ruleRefExpr{
										pos:    position{line: 60, col: 8, offset: 1339},
										offset: 2,
									},
								},
								&ruleRefExpr{
									pos:    position{line: 60, col: 19, offset: 1350},
									offset: 1,
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Equality",
			pos:  position{line: 73, col: 1, offset: 1454},
			expr: &actionExpr{
				pos: position{line: 73, col: 13, offset: 1466},
				run: (*parser).callonEquality1,
				expr: &seqExpr{
					pos: position{line: 73, col: 13, offset: 1466},
					exprs: []any{
						&ruleRefExpr{
							pos:    position{line: 73, col: 13, offset: 1466},
							offset: 45,
						},
						&labeledExpr{
							pos:   position{line: 73, col: 15, offset: 1468},
							label: "left",
							expr: &ruleRefExpr{
								pos:    position{line: 73, col: 20, offset: 1473},
								offset: 7,
							},
						},
						&labeledExpr{
							pos:   position{line: 73, col: 28, offset: 1481},
							label: "right",
							expr: &zeroOrMoreExpr{
								pos: position{line: 73, col: 34, offset: 1487},
								expr: &ruleRefExpr{
									pos:    position{line: 73, col: 34, offset: 1487},
									offset: 5,
								},
							},
						},
						&ruleRefExpr{
							pos:    position{line: 73, col: 44, offset: 1497},
							offset: 45,
						},
					},
				},
			},
		},
		{
			name: "EqualsOp",
			pos:  position{line: 91, col: 1, offset: 1890},
			expr: &actionExpr{
				pos: position{line: 91, col: 13, offset: 1902},
				run: (*parser).callonEqualsOp1,
				expr: &seqExpr{
					pos: position{line: 91, col: 13, offset: 1902},
					exprs: []any{
						&ruleRefExpr{
							pos:    position{line: 91, col: 13, offset: 1902},
							offset: 45,
						},
						&labeledExpr{
							pos:   position{line: 91, col: 15, offset: 1904},
							label: "equals",
							expr: &choiceExpr{
								pos: position{line: 91, col: 23, offset: 1912},
								alternatives: []any{
									&litMatcher{
										pos:        position{line: 91, col: 23, offset: 1912},
										val:        "==",
										ignoreCase: false,
										want:       "\"==\"",
									},
									&litMatcher{
										pos:        position{line: 91, col: 28, offset: 1917},
										val:        "!=",
										ignoreCase: false,
										want:       "\"!=\"",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:    position{line: 91, col: 34, offset: 1923},
							offset: 45,
						},
						&labeledExpr{
							pos:   position{line: 91, col: 36, offset: 1925},
							label: "f",
							expr: &ruleRefExpr{
								pos:    position{line: 91, col: 38, offset: 1927},
								offset: 7,
							},
						},
					},
				},
			},
		},
		{
			name: "LogicalTerm",
			pos:  position{line: 99, col: 1, offset: 2079},
			expr: &choiceExpr{
				pos: position{line: 99, col: 16, offset: 2094},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 99, col: 16, offset: 2094},
						run: (*parser).callonLogicalTerm2,
						expr: &seqExpr{
							pos: position{line: 99, col: 16, offset: 2094},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 99, col: 16, offset: 2094},
									label: "not",
									expr: &zeroOrOneExpr{
										pos: position{line: 99, col: 20, offset: 2098},
										expr: &litMatcher{
											pos:        position{line: 99, col: 20, offset: 2098},
											val:        "!",
											ignoreCase: false,
											want:       "\"!\"",
										},
									},
								},
								&litMatcher{
									pos:        position{line: 99, col: 25, offset: 2103},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&ruleRefExpr{
									pos:    position{line: 99, col: 29, offset: 2107},
									offset: 45,
								},
								&labeledExpr{
									pos:   position{line: 99, col: 32, offset: 2110},
									label: "eq",
									expr: &ruleRefExpr{
										pos:    position{line: 99, col: 35, offset: 2113},
										offset: 4,
									},
								},
								&ruleRefExpr{
									pos:    position{line: 99, col: 44, offset: 2122},
									offset: 45,
								},
								&litMatcher{
									pos:        position{line: 99, col: 46, offset: 2124},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 109, col: 5, offset: 2361},
						run: (*parser).callonLogicalTerm13,
						expr: &labeledExpr{
							pos:   position{line: 109, col: 5, offset: 2361},
							label: "feature",
							expr: &ruleRefExpr{
								pos:    position{line: 109, col: 13, offset: 2369},
								offset: 30,
							},
						},
					},
					&actionExpr{
						pos: position{line: 111, col: 5, offset: 2410},
						run: (*parser).callonLogicalTerm16,
						expr: &labeledExpr{
							pos:   position{line: 111, col: 5, offset: 2410},
							label: "reference",
							expr: &ruleRefExpr{
								pos:    position{line: 111, col: 15, offset: 2420},
								offset: 25,
							},
						},
					},
					&actionExpr{
						pos: position{line: 113, col: 5, offset: 2465},
						run: (*parser).callonLogicalTerm19,
						expr: &labeledExpr{
							pos:   position{line: 113, col: 5, offset: 2465},
							label: "identifier",
							expr: &ruleRefExpr{
								pos:    position{line: 113, col: 16, offset: 2476},
								offset: 22,
							},
						},
					},
				},
			},
		},
		{
			name: "Logical",
			pos:  position{line: 117, col: 1, offset: 2523},
			expr: &ruleRefExpr{
				pos:    position{line: 117, col: 12, offset: 2534},
				offset: 8,
			},
		},
		{
			name: "Or",
			pos:  position{line: 119, col: 1, offset: 2538},
			expr: &actionExpr{
				pos: position{line: 119, col: 7, offset: 2544},
				run: (*parser).callonOr1,
				expr: &seqExpr{
					pos: position{line: 119, col: 7, offset: 2544},
					exprs: []any{
						&ruleRefExpr{
							pos:    position{line: 119, col: 7, offset: 2544},
							offset: 45,
						},
						&labeledExpr{
							pos:   position{line: 119, col: 9, offset: 2546},
							label: "left",
							expr: &ruleRefExpr{
								pos:    position{line: 119, col: 14, offset: 2551},
								offset: 10,
							},
						},
						&ruleRefExpr{
							pos:    position{line: 119, col: 18, offset: 2555},
							offset: 45,
						},
						&labeledExpr{
							pos:   position{line: 119, col: 20, offset: 2557},
							label: "right",
							expr: &zeroOrMoreExpr{
								pos: position{line: 119, col: 26, offset: 2563},
								expr: &ruleRefExpr{
									pos:    position{line: 119, col: 26, offset: 2563},
									offset: 9,
								},
							},
						},
						&ruleRefExpr{
							pos:    position{line: 119, col: 32, offset: 2569},
							offset: 45,
						},
					},
				},
			},
		},
		{
			name: "OrOp",
			pos:  position{line: 131, col: 1, offset: 2800},
			expr: &actionExpr{
				pos: position{line: 131, col: 9, offset: 2808},
				run: (*parser).callonOrOp1,
				expr: &seqExpr{
					pos: position{line: 131, col: 9, offset: 2808},
					exprs: []any{
						&ruleRefExpr{
							pos:    position{line: 131, col: 9, offset: 2808},
							offset: 45,
						},
						&litMatcher{
							pos:        position{line: 131, col: 11, offset: 2810},
							val:        "|",
							ignoreCase: false,
							want:       "\"|\"",
						},
						&ruleRefExpr{
							pos:    position{line: 131, col: 15, offset: 2814},
							offset: 45,
						},
						&labeledExpr{
							pos:   position{line: 131, col: 17, offset: 2816},
							label: "f",
							expr: &ruleRefExpr{
								pos:    position{line: 131, col: 19, offset: 2818},
								offset: 10,
							},
						},
					},
				},
			},
		},
		{
			name: "Xor",
			pos:  position{line: 136, col: 1, offset: 2875},
			expr: &actionExpr{
				pos: position{line: 136, col: 8, offset: 2882},
				run: (*parser).callonXor1,
				expr: &seqExpr{
					pos: position{line: 136, col: 8, offset: 2882},
					exprs: []any{
						&ruleRefExpr{
							pos:    position{line: 136, col: 8, offset: 2882},
							offset: 45,
						},
						&labeledExpr{
							pos:   position{line: 136, col: 10, offset: 2884},
							label: "left",
							expr: &ruleRefExpr{
								pos:    position{line: 136, col: 15, offset: 2889},
								offset: 12,
							},
						},
						&ruleRefExpr{
							pos:    position{line: 136, col: 19, offset: 2893},
							offset: 45,
						},
						&labeledExpr{
							pos:   position{line: 136, col: 21, offset: 2895},
							label: "right",
							expr: &zeroOrMoreExpr{
								pos: position{line: 136, col: 27, offset: 2901},
								expr: &ruleRefExpr{
									pos:    position{line: 136, col: 27, offset: 2901},
									offset: 11,
								},
							},
						},
						&ruleRefExpr{
							pos:    position{line: 136, col: 34, offset: 2908},
							offset: 45,
						},
					},
				},
			},
		},
		{
			name: "XorOp",
			pos:  position{line: 148, col: 1, offset: 3142},
			expr: &actionExpr{
				pos: position{line: 148, col: 10, offset: 3151},
				run: (*parser).callonXorOp1,
				expr: &seqExpr{
					pos: position{line: 148, col: 10, offset: 3151},
					exprs: []any{
						&ruleRefExpr{
							pos:    position{line: 148, col: 10, offset: 3151},
							offset: 45,
						},
						&litMatcher{
							pos:        position{line: 148, col: 12, offset: 3153},
							val:        "^",
							ignoreCase: false,
							want:       "\"^\"",
						},
						&ruleRefExpr{
							pos:    position{line: 148, col: 16, offset: 3157},
							offset: 45,
						},
						&labeledExpr{
							pos:   position{line: 148, col: 18, offset: 3159},
							label: "f",
							expr: &ruleRefExpr{
								pos:    position{line: 148, col: 20, offset: 3161},
								offset: 12,
							},
						},
					},
				},
			},
		},
		{
			name: "And",
			pos:  position{line: 153, col: 1, offset: 3217},
			expr: &actionExpr{
				pos: position{line: 153, col: 8, offset: 3224},
				run: (*parser).callonAnd1,
				expr: &seqExpr{
					pos: position{line: 153, col: 8, offset: 3224},
					exprs: []any{
						&ruleRefExpr{
							pos:    position{line: 153, col: 8, offset: 3224},
							offset: 45,
						},
						&labeledExpr{
							pos:   position{line: 153, col: 10, offset: 3226},
							label: "left",
							expr: &ruleRefExpr{
								pos:    position{line: 153, col: 15, offset: 3231},
								offset: 6,
							},
						},
						&ruleRefExpr{
							pos:    position{line: 153, col: 27, offset: 3243},
							offset: 45,
						},
						&labeledExpr{
							pos:   position{line: 153, col: 29, offset: 3245},
							label: "right",
							expr: &zeroOrMoreExpr{
								pos: position{line: 153, col: 35, offset: 3251},
								expr: &ruleRefExpr{
									pos:    position{line: 153, col: 35, offset: 3251},
									offset: 13,
								},
							},
						},
						&ruleRefExpr{
							pos:    position{line: 153, col: 42, offset: 3258},
							offset: 45,
						},
					},
				},
			},
		},
		{
			name: "AndOp",
			pos:  position{line: 165, col: 1, offset: 3491},
			expr: &actionExpr{
				pos: position{line: 165, col: 10, offset: 3500},
				run: (*parser).callonAndOp1,
				expr: &seqExpr{
					pos: position{line: 165, col: 10, offset: 3500},
					exprs: []any{
						&ruleRefExpr{
							pos:    position{line: 165, col: 10, offset: 3500},
							offset: 45,
						},
						&litMatcher{
							pos:        position{line: 165, col: 12, offset: 3502},
							val:        "&",
							ignoreCase: false,
							want:       "\"&\"",
						},
						&ruleRefExpr{
							pos:    position{line: 165, col: 16, offset: 3506},
							offset: 45,
						},
						&labeledExpr{
							pos:   position{line: 165, col: 18, offset: 3508},
							label: "f",
							expr: &ruleRefExpr{
								pos:    position{line: 165, col: 20, offset: 3510},
								offset: 6,
							},
						},
					},
				},
			},
		},
		{
			name: "Float",
			pos:  position{line: 173, col: 1, offset: 3578},
			expr: &actionExpr{
				pos: position{line: 173, col: 10, offset: 3587},
				run: (*parser).callonFloat1,
				expr: &seqExpr{
					pos: position{line: 173, col: 10, offset: 3587},
					exprs: []any{
						&ruleRefExpr{
							pos:    position{line: 173, col: 10, offset: 3587},
							offset: 15,
						},
						&seqExpr{
							pos: position{line: 173, col: 19, offset: 3596},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 173, col: 19, offset: 3596},
									val:        ".",
									ignoreCase: false,
									want:       "\".\"",
								},
								&oneOrMoreExpr{
									pos: position{line: 173, col: 23, offset: 3600},
									expr: &charClassMatcher{
										pos:        position{line: 173, col: 23, offset: 3600},
										val:        "[0-9]",
										ranges:     []rune{'0', '9'},
										ignoreCase: false,
										inverted:   false,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 177, col: 1, offset: 3659},
			expr: &actionExpr{
				pos: position{line: 177, col: 12, offset: 3670},
				run: (*parser).callonInteger1,
				expr: &seqExpr{
					pos: position{line: 177, col: 12, offset: 3670},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 177, col: 12, offset: 3670},
							label: "sign",
							expr: &zeroOrOneExpr{
								pos: position{line: 177, col: 17, offset: 3675},
								expr: &choiceExpr{
									pos: position{line: 177, col: 18, offset: 3676},
									alternatives: []any{
										&litMatcher{
											pos:        position{line: 177, col: 18, offset: 3676},
											val:        "-",
											ignoreCase: false,
											want:       "\"-\"",
										},
										&litMatcher{
											pos:        position{line: 177, col: 22, offset: 3680},
											val:        "+",
											ignoreCase: false,
											want:       "\"+\"",
										},
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 177, col: 28, offset: 3686},
							label: "digits",
							expr: &ruleRefExpr{
								pos:    position{line: 177, col: 35, offset: 3693},
								offset: 17,
							},
						},
					},
				},
			},
		},
		{
			name: "Hex",
			pos:  position{line: 181, col: 1, offset: 3755},
			expr: &actionExpr{
				pos: position{line: 181, col: 8, offset: 3762},
				run: (*parser).callonHex1,
				expr: &seqExpr{
					pos: position{line: 181, col: 8, offset: 3762},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 181, col: 8, offset: 3762},
							val:        "0x",
							ignoreCase: true,
							want:       "\"0x\"i",
						},
						&labeledExpr{
							pos:   position{line: 181, col: 14, offset: 3768},
							label: "hex",
							expr: &oneOrMoreExpr{
								pos: position{line: 181, col: 18, offset: 3772},
								expr: &charClassMatcher{
									pos:        position{line: 181, col: 18, offset: 3772},
									val:        "[0-9A-Fa-f]",
									ranges:     []rune{'0', '9', 'A', 'F', 'a', 'f'},
									ignoreCase: false,
									inverted:   false,
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Digits",
			pos:  position{line: 189, col: 1, offset: 3934},
			expr: &actionExpr{
				pos: position{line: 189, col: 11, offset: 3944},
				run: (*parser).callonDigits1,
				expr: &oneOrMoreExpr{
					pos: position{line: 189, col: 11, offset: 3944},
					expr: &charClassMatcher{
						pos:        position{line: 189, col: 11, offset: 3944},
						val:        "[0-9]",
						ranges:     []rune{'0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "Operator",
			pos:  position{line: 197, col: 1, offset: 4009},
			expr: &choiceExpr{
				pos: position{line: 199, col: 6, offset: 4032},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 199, col: 7, offset: 4033},
						run: (*parser).callonOperator2,
						expr: &litMatcher{
							pos:        position{line: 199, col: 7, offset: 4033},
							val:        "<",
							ignoreCase: false,
							want:       "\"<\"",
						},
					},
					&actionExpr{
						pos: position{line: 200, col: 8, offset: 4089},
						run: (*parser).callonOperator4,
						expr: &litMatcher{
							pos:        position{line: 200, col: 8, offset: 4089},
							val:        "<=",
							ignoreCase: false,
							want:       "\"<=\"",
						},
					},
					&actionExpr{
						pos: position{line: 201, col: 8, offset: 4152},
						run: (*parser).callonOperator6,
						expr: &litMatcher{
							pos:        position{line: 201, col: 8, offset: 4152},
							val:        ">",
							ignoreCase: false,
							want:       "\">\"",
						},
					},
					&actionExpr{
						pos: position{line: 202, col: 8, offset: 4211},
						run: (*parser).callonOperator8,
						expr: &litMatcher{
							pos:        position{line: 202, col: 8, offset: 4211},
							val:        ">=",
							ignoreCase: false,
							want:       "\">=\"",
						},
					},
				},
			},
		},
		{
			name: "ComparisonTerm",
			pos:  position{line: 204, col: 1, offset: 4271},
			expr: &choiceExpr{
				pos: position{line: 204, col: 19, offset: 4289},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 204, col: 19, offset: 4289},
						run: (*parser).callonComparisonTerm2,
						expr: &labeledExpr{
							pos:   position{line: 204, col: 19, offset: 4289},
							label: "feature",
							expr: &ruleRefExpr{
								pos:    position{line: 204, col: 27, offset: 4297},
								offset: 31,
							},
						},
					},
					&actionExpr{
						pos: position{line: 206, col: 5, offset: 4341},
						run: (*parser).callonComparisonTerm5,
						expr: &labeledExpr{
							pos:   position{line: 206, col: 5, offset: 4341},
							label: "reference",
							expr: &ruleRefExpr{
								pos:    position{line: 206, col: 15, offset: 4351},
								offset: 26,
							},
						},
					},
					&actionExpr{
						pos: position{line: 208, col: 5, offset: 4399},
						run: (*parser).callonComparisonTerm8,
						expr: &labeledExpr{
							pos:   position{line: 208, col: 5, offset: 4399},
							label: "identifier",
							expr: &ruleRefExpr{
								pos:    position{line: 208, col: 16, offset: 4410},
								offset: 23,
							},
						},
					},
					&actionExpr{
						pos: position{line: 210, col: 5, offset: 4460},
						run: (*parser).callonComparisonTerm11,
						expr: &labeledExpr{
							pos:   position{line: 210, col: 5, offset: 4460},
							label: "number",
							expr: &ruleRefExpr{
								pos:    position{line: 210, col: 12, offset: 4467},
								offset: 21,
							},
						},
					},
				},
			},
		},
		{
			name: "Comparison",
			pos:  position{line: 214, col: 1, offset: 4508},
			expr: &actionExpr{
				pos: position{line: 214, col: 15, offset: 4522},
				run: (*parser).callonComparison1,
				expr: &seqExpr{
					pos: position{line: 214, col: 15, offset: 4522},
					exprs: []any{
						&ruleRefExpr{
							pos:    position{line: 214, col: 15, offset: 4522},
							offset: 45,
						},
						&labeledExpr{
							pos:   position{line: 214, col: 17, offset: 4524},
							label: "left",
							expr: &ruleRefExpr{
								pos:    position{line: 214, col: 22, offset: 4529},
								offset: 19,
							},
						},
						&ruleRefExpr{
							pos:    position{line: 214, col: 37, offset: 4544},
							offset: 45,
						},
						&labeledExpr{
							pos:   position{line: 214, col: 39, offset: 4546},
							label: "op",
							expr: &ruleRefExpr{
								pos:    position{line: 214, col: 42, offset: 4549},
								offset: 18,
							},
						},
						&ruleRefExpr{
							pos:    position{line: 214, col: 51, offset: 4558},
							offset: 45,
						},
						&labeledExpr{
							pos:   position{line: 214, col: 53, offset: 4560},
							label: "right",
							expr: &ruleRefExpr{
								pos:    position{line: 214, col: 59, offset: 4566},
								offset: 19,
							},
						},
						&ruleRefExpr{
							pos:    position{line: 214, col: 74, offset: 4581},
							offset: 45,
						},
					},
				},
			},
		},
		{
			name: "NumberValue",
			pos:  position{line: 221, col: 1, offset: 4767},
			expr: &choiceExpr{
				pos: position{line: 221, col: 17, offset: 4783},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 221, col: 17, offset: 4783},
						run: (*parser).callonNumberValue2,
						expr: &labeledExpr{
							pos:   position{line: 221, col: 17, offset: 4783},
							label: "val",
							expr: &ruleRefExpr{
								pos:    position{line: 221, col: 22, offset: 4788},
								offset: 16,
							},
						},
					},
					&actionExpr{
						pos: position{line: 224, col: 7, offset: 4868},
						run: (*parser).callonNumberValue5,
						expr: &labeledExpr{
							pos:   position{line: 224, col: 7, offset: 4868},
							label: "val",
							expr: &ruleRefExpr{
								pos:    position{line: 224, col: 11, offset: 4872},
								offset: 14,
							},
						},
					},
					&actionExpr{
						pos: position{line: 227, col: 11, offset: 4973},
						run: (*parser).callonNumberValue8,
						expr: &labeledExpr{
							pos:   position{line: 227, col: 11, offset: 4973},
							label: "val",
							expr: &ruleRefExpr{
								pos:    position{line: 227, col: 15, offset: 4977},
								offset: 15,
							},
						},
					},
				},
			},
		},
		{
			name: "IdentifierOp",
			pos:  position{line: 234, col: 1, offset: 5063},
			expr: &actionExpr{
				pos: position{line: 234, col: 17, offset: 5079},
				run: (*parser).callonIdentifierOp1,
				expr: &seqExpr{
					pos: position{line: 234, col: 17, offset: 5079},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 234, col: 17, offset: 5079},
							label: "not",
							expr: &zeroOrOneExpr{
								pos: position{line: 234, col: 21, offset: 5083},
								expr: &litMatcher{
									pos:        position{line: 234, col: 21, offset: 5083},
									val:        "!",
									ignoreCase: false,
									want:       "\"!\"",
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 234, col: 26, offset: 5088},
							label: "identifier",
							expr: &ruleRefExpr{
								pos:    position{line: 234, col: 37, offset: 5099},
								offset: 24,
							},
						},
					},
				},
			},
		},
		{
			name: "IdentifierValue",
			pos:  position{line: 243, col: 1, offset: 5255},
			expr: &actionExpr{
				pos: position{line: 243, col: 20, offset: 5274},
				run: (*parser).callonIdentifierValue1,
				expr: &labeledExpr{
					pos:   position{line: 243, col: 20, offset: 5274},
					label: "identifier",
					expr: &ruleRefExpr{
						pos:    position{line: 243, col: 31, offset: 5285},
						offset: 24,
					},
				},
			},
		},
		{
			name: "Identifier",
			pos:  position{line: 248, col: 1, offset: 5372},
			expr: &actionExpr{
				pos: position{line: 248, col: 15, offset: 5386},
				run: (*parser).callonIdentifier1,
				expr: &seqExpr{
					pos: position{line: 248, col: 15, offset: 5386},
					exprs: []any{
						&ruleRefExpr{
							pos:    position{line: 248, col: 15, offset: 5386},
							offset: 40,
						},
						&zeroOrMoreExpr{
							pos: position{line: 248, col: 26, offset: 5397},
							expr: &seqExpr{
								pos: position{line: 248, col: 27, offset: 5398},
								exprs: []any{
									&litMatcher{
										pos:        position{line: 248, col: 27, offset: 5398},
										val:        "-",
										ignoreCase: false,
										want:       "\"-\"",
									},
									&ruleRefExpr{
										pos:    position{line: 248, col: 31, offset: 5402},
										offset: 40,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ReferenceOp",
			pos:  position{line: 252, col: 1, offset: 5455},
			expr: &actionExpr{
				pos: position{line: 252, col: 16, offset: 5470},
				run: (*parser).callonReferenceOp1,
				expr: &seqExpr{
					pos: position{line: 252, col: 16, offset: 5470},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 252, col: 16, offset: 5470},
							label: "not",
							expr: &zeroOrOneExpr{
								pos: position{line: 252, col: 20, offset: 5474},
								expr: &litMatcher{
									pos:        position{line: 252, col: 20, offset: 5474},
									val:        "!",
									ignoreCase: false,
									want:       "\"!\"",
								},
							},
						},
						&litMatcher{
							pos:        position{line: 252, col: 25, offset: 5479},
							val:        "<<",
							ignoreCase: false,
							want:       "\"<<\"",
						},
						&labeledExpr{
							pos:   position{line: 252, col: 30, offset: 5484},
							label: "reference",
							expr: &ruleRefExpr{
								pos:    position{line: 252, col: 40, offset: 5494},
								offset: 29,
							},
						},
						&labeledExpr{
							pos:   position{line: 252, col: 52, offset: 5506},
							label: "label",
							expr: &zeroOrOneExpr{
								pos: position{line: 252, col: 58, offset: 5512},
								expr: &ruleRefExpr{
									pos:    position{line: 252, col: 59, offset: 5513},
									offset: 27,
								},
							},
						},
						&litMatcher{
							pos:        position{line: 252, col: 77, offset: 5531},
							val:        ">>",
							ignoreCase: false,
							want:       "\">>\"",
						},
					},
				},
			},
		},
		{
			name: "ReferenceValue",
			pos:  position{line: 263, col: 1, offset: 5743},
			expr: &actionExpr{
				pos: position{line: 263, col: 19, offset: 5761},
				run: (*parser).callonReferenceValue1,
				expr: &seqExpr{
					pos: position{line: 263, col: 19, offset: 5761},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 263, col: 19, offset: 5761},
							val:        "<<",
							ignoreCase: false,
							want:       "\"<<\"",
						},
						&labeledExpr{
							pos:   position{line: 263, col: 24, offset: 5766},
							label: "reference",
							expr: &ruleRefExpr{
								pos:    position{line: 263, col: 34, offset: 5776},
								offset: 29,
							},
						},
						&labeledExpr{
							pos:   position{line: 263, col: 46, offset: 5788},
							label: "label",
							expr: &zeroOrOneExpr{
								pos: position{line: 263, col: 52, offset: 5794},
								expr: &ruleRefExpr{
									pos:    position{line: 263, col: 53, offset: 5795},
									offset: 27,
								},
							},
						},
						&litMatcher{
							pos:        position{line: 263, col: 71, offset: 5813},
							val:        ">>",
							ignoreCase: false,
							want:       "\">>\"",
						},
					},
				},
			},
		},
		{
			name: "ReferenceLabel",
			pos:  position{line: 271, col: 1, offset: 5972},
			expr: &actionExpr{
				pos: position{line: 271, col: 19, offset: 5990},
				run: (*parser).callonReferenceLabel1,
				expr: &seqExpr{
					pos: position{line: 271, col: 19, offset: 5990},
					exprs: []any{
						&ruleRefExpr{
							pos:    position{line: 271, col: 19, offset: 5990},
							offset: 45,
						},
						&ruleRefExpr{
							pos:    position{line: 271, col: 21, offset: 5992},
							offset: 46,
						},
						&ruleRefExpr{
							pos:    position{line: 271, col: 27, offset: 5998},
							offset: 45,
						},
						&labeledExpr{
							pos:   position{line: 271, col: 29, offset: 6000},
							label: "label",
							expr: &ruleRefExpr{
								pos:    position{line: 271, col: 35, offset: 6006},
								offset: 28,
							},
						},
						&andExpr{
							pos: position{line: 271, col: 50, offset: 6021},
							expr: &litMatcher{
								pos:        position{line: 271, col: 51, offset: 6022},
								val:        ">>",
								ignoreCase: false,
								want:       "\">>\"",
							},
						},
					},
				},
			},
		},
		{
			name: "ReferenceText",
			pos:  position{line: 275, col: 1, offset: 6067},
			expr: &actionExpr{
				pos: position{line: 275, col: 18, offset: 6084},
				run: (*parser).callonReferenceText1,
				expr: &oneOrMoreExpr{
					pos: position{line: 275, col: 18, offset: 6084},
					expr: &seqExpr{
						pos: position{line: 275, col: 19, offset: 6085},
						exprs: []any{
							&notExpr{
								pos: position{line: 275, col: 19, offset: 6085},
								expr: &litMatcher{
									pos:        position{line: 275, col: 20, offset: 6086},
									val:        ">>",
									ignoreCase: false,
									want:       "\">>\"",
								},
							},
							&anyMatcher{
								line: 275, col: 25, offset: 6091,
							},
						},
					},
				},
			},
		},
		{
			name: "ReferenceId",
			pos:  position{line: 279, col: 1, offset: 6136},
			expr: &actionExpr{
				pos: position{line: 279, col: 16, offset: 6151},
				run: (*parser).callonReferenceId1,
				expr: &seqExpr{
					pos: position{line: 279, col: 16, offset: 6151},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 279, col: 16, offset: 6151},
							val:        "ref_",
							ignoreCase: false,
							want:       "\"ref_\"",
						},
						&ruleRefExpr{
							pos:    position{line: 279, col: 23, offset: 6158},
							offset: 40,
						},
					},
				},
			},
		},
		{
			name: "FeatureOp",
			pos:  position{line: 283, col: 1, offset: 6209},
			expr: &actionExpr{
				pos: position{line: 283, col: 14, offset: 6222},
				run: (*parser).callonFeatureOp1,
				expr: &seqExpr{
					pos: position{line: 283, col: 14, offset: 6222},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 283, col: 14, offset: 6222},
							label: "not",
							expr: &zeroOrOneExpr{
								pos: position{line: 283, col: 18, offset: 6226},
								expr: &litMatcher{
									pos:        position{line: 283, col: 18, offset: 6226},
									val:        "!",
									ignoreCase: false,
									want:       "\"!\"",
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 283, col: 23, offset: 6231},
							label: "feature",
							expr: &ruleRefExpr{
								pos:    position{line: 283, col: 31, offset: 6239},
								offset: 32,
							},
						},
					},
				},
			},
		},
		{
			name: "FeatureValue",
			pos:  position{line: 296, col: 1, offset: 6518},
			expr: &actionExpr{
				pos: position{line: 296, col: 17, offset: 6534},
				run: (*parser).callonFeatureValue1,
				expr: &labeledExpr{
					pos:   position{line: 296, col: 17, offset: 6534},
					label: "feature",
					expr: &ruleRefExpr{
						pos:    position{line: 296, col: 25, offset: 6542},
						offset: 32,
					},
				},
			},
		},
		{
			name: "Feature",
			pos:  position{line: 307, col: 1, offset: 6769},
			expr: &actionExpr{
				pos: position{line: 307, col: 12, offset: 6780},
				run: (*parser).callonFeature1,
				expr: &seqExpr{
					pos: position{line: 307, col: 12, offset: 6780},
					exprs: []any{
						&charClassMatcher{
							pos:        position{line: 307, col: 12, offset: 6780},
							val:        "[A-Z]",
							ranges:     []rune{'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
						&oneOrMoreExpr{
							pos: position{line: 307, col: 17, offset: 6785},
							expr: &charClassMatcher{
								pos:        position{line: 307, col: 17, offset: 6785},
								val:        "[A-Z0-9_]",
								chars:      []rune{'_'},
								ranges:     []rune{'A', 'Z', '0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&andExpr{
							pos: position{line: 307, col: 28, offset: 6796},
							expr: &choiceExpr{
								pos: position{line: 307, col: 30, offset: 6798},
								alternatives: []any{
									&notExpr{
										pos: position{line: 307, col: 30, offset: 6798},
										expr: &charClassMatcher{
											pos:        position{line: 307, col: 31, offset: 6799},
											val:        "[A-Za-z0-9_]",
											chars:      []rune{'_'},
											ranges:     []rune{'A', 'Z', 'a', 'z', '0', '9'},
											ignoreCase: false,
											inverted:   false,
										},
									},
									&ruleRefExpr{
										pos:    position{line: 307, col: 46, offset: 6814},
										offset: 47,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ChoiceRange",
			pos:  position{line: 315, col: 1, offset: 6859},
			expr: &actionExpr{
				pos: position{line: 315, col: 16, offset: 6874},
				run: (*parser).callonChoiceRange1,
				expr: &seqExpr{
					pos: position{line: 315, col: 16, offset: 6874},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 315, col: 16, offset: 6874},
							label: "lower",
							expr: &ruleRefExpr{
								pos:    position{line: 315, col: 22, offset: 6880},
								offset: 15,
							},
						},
						&litMatcher{
							pos:        position{line: 315, col: 30, offset: 6888},
							val:        "-",
							ignoreCase: false,
							want:       "\"-\"",
						},
						&labeledExpr{
							pos:   position{line: 315, col: 34, offset: 6892},
							label: "upper",
							expr: &ruleRefExpr{
								pos:    position{line: 315, col: 40, offset: 6898},
								offset: 15,
							},
						},
					},
				},
			},
		},
		{
			name: "ChoiceMin",
			pos:  position{line: 327, col: 1, offset: 7221},
			expr: &actionExpr{
				pos: position{line: 327, col: 14, offset: 7234},
				run: (*parser).callonChoiceMin1,
				expr: &seqExpr{
					pos: position{line: 327, col: 14, offset: 7234},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 327, col: 14, offset: 7234},
							label: "limit",
							expr: &zeroOrOneExpr{
								pos: position{line: 327, col: 20, offset: 7240},
								expr: &ruleRefExpr{
									pos:    position{line: 327, col: 20, offset: 7240},
									offset: 15,
								},
							},
						},
						&litMatcher{
							pos:        position{line: 327, col: 29, offset: 7249},
							val:        "+",
							ignoreCase: false,
							want:       "\"+\"",
						},
					},
				},
			},
		},
		{
			name: "ChoiceMax",
			pos:  position{line: 338, col: 1, offset: 7492},
			expr: &actionExpr{
				pos: position{line: 338, col: 14, offset: 7505},
				run: (*parser).callonChoiceMax1,
				expr: &seqExpr{
					pos: position{line: 338, col: 14, offset: 7505},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 338, col: 14, offset: 7505},
							label: "limit",
							expr: &zeroOrOneExpr{
								pos: position{line: 338, col: 20, offset: 7511},
								expr: &ruleRefExpr{
									pos:    position{line: 338, col: 20, offset: 7511},
									offset: 15,
								},
							},
						},
						&litMatcher{
							pos:        position{line: 338, col: 29, offset: 7520},
							val:        "-",
							ignoreCase: false,
							want:       "\"-\"",
						},
					},
				},
			},
		},
		{
			name: "ChoiceExact",
			pos:  position{line: 349, col: 1, offset: 7761},
			expr: &actionExpr{
				pos: position{line: 349, col: 16, offset: 7776},
				run: (*parser).callonChoiceExact1,
				expr: &labeledExpr{
					pos:   position{line: 349, col: 16, offset: 7776},
					label: "limit",
					expr: &ruleRefExpr{
						pos:    position{line: 349, col: 22, offset: 7782},
						offset: 15,
					},
				},
			},
		},
		{
			name: "ChoiceLimit",
			pos:  position{line: 357, col: 1, offset: 7953},
			expr: &actionExpr{
				pos: position{line: 357, col: 16, offset: 7968},
				run: (*parser).callonChoiceLimit1,
				expr: &labeledExpr{
					pos:   position{line: 357, col: 16, offset: 7968},
					label: "limit",
					expr: &choiceExpr{
						pos: position{line: 357, col: 23, offset: 7975},
						alternatives: []any{
							&ruleRefExpr{
								pos:    position{line: 357, col: 23, offset: 7975},
								offset: 33,
							},
							&ruleRefExpr{
								pos:    position{line: 357, col: 37, offset: 7989},
								offset: 34,
							},
							&ruleRefExpr{
								pos:    position{line: 357, col: 49, offset: 8001},
								offset: 35,
							},
							&ruleRefExpr{
								pos:    position{line: 357, col: 61, offset: 8013},
								offset: 36,
							},
						},
					},
				},
			},
		},
		{
			name: "Set",
			pos:  position{line: 361, col: 1, offset: 8067},
			expr: &actionExpr{
				pos: position{line: 361, col: 8, offset: 8074},
				run: (*parser).callonSet1,
				expr: &oneOrMoreExpr{
					pos: position{line: 361, col: 8, offset: 8074},
					expr: &charClassMatcher{
						pos:        position{line: 361, col: 8, offset: 8074},
						val:        "[a-z]",
						ranges:     []rune{'a', 'z'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "Choice",
			pos:  position{line: 365, col: 1, offset: 8117},
			expr: &actionExpr{
				pos: position{line: 365, col: 11, offset: 8127},
				run: (*parser).callonChoice1,
				expr: &seqExpr{
					pos: position{line: 365, col: 11, offset: 8127},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 365, col: 11, offset: 8127},
							val:        ".",
							ignoreCase: false,
							want:       "\".\"",
						},
						&labeledExpr{
							pos:   position{line: 365, col: 15, offset: 8131},
							label: "set",
							expr: &ruleRefExpr{
								pos:    position{line: 365, col: 19, offset: 8135},
								offset: 38,
							},
						},
						&labeledExpr{
							pos:   position{line: 365, col: 23, offset: 8139},
							label: "limit",
							expr: &zeroOrOneExpr{
								pos: position{line: 365, col: 29, offset: 8145},
								expr: &ruleRefExpr{
									pos:    position{line: 365, col: 29, offset: 8145},
									offset: 37,
								},
							},
						},
					},
				},
			},
		},
		{
			name: "PascalCase",
			pos:  position{line: 381, col: 1, offset: 8460},
			expr: &actionExpr{
				pos: position{line: 381, col: 15, offset: 8474},
				run: (*parser).callonPascalCase1,
				expr: &seqExpr{
					pos: position{line: 381, col: 15, offset: 8474},
					exprs: []any{
						&oneOrMoreExpr{
							pos: position{line: 381, col: 15, offset: 8474},
							expr: &ruleRefExpr{
								pos:    position{line: 381, col: 15, offset: 8474},
								offset: 41,
							},
						},
						&zeroOrMoreExpr{
							pos: position{line: 381, col: 28, offset: 8487},
							expr: &ruleRefExpr{
								pos:    position{line: 381, col: 28, offset: 8487},
								offset: 41,
							},
						},
					},
				},
			},
		},
		{
			name: "Capitalized",
			pos:  position{line: 386, col: 1, offset: 8538},
			expr: &actionExpr{
				pos: position{line: 386, col: 16, offset: 8553},
				run: (*parser).callonCapitalized1,
				expr: &seqExpr{
					pos: position{line: 386, col: 16, offset: 8553},
					exprs: []any{
						&oneOrMoreExpr{
							pos: position{line: 386, col: 16, offset: 8553},
							expr: &ruleRefExpr{
								pos:    position{line: 386, col: 16, offset: 8553},
								offset: 42,
							},
						},
						&zeroOrMoreExpr{
							pos: position{line: 386, col: 27, offset: 8564},
							expr: &ruleRefExpr{
								pos:    position{line: 386, col: 27, offset: 8564},
								offset: 43,
							},
						},
					},
				},
			},
		},
		{
			name: "Uppercase",
			pos:  position{line: 390, col: 1, offset: 8612},
			expr: &actionExpr{
				pos: position{line: 390, col: 14, offset: 8625},
				run: (*parser).callonUppercase1,
				expr: &charClassMatcher{
					pos:        position{line: 390, col: 14, offset: 8625},
					val:        "[A-Z]",
					ranges:     []rune{'A', 'Z'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "Lowercase",
			pos:  position{line: 394, col: 1, offset: 8668},
			expr: &actionExpr{
				pos: position{line: 394, col: 14, offset: 8681},
				run: (*parser).callonLowercase1,
				expr: &charClassMatcher{
					pos:        position{line: 394, col: 14, offset: 8681},
					val:        "[a-z]",
					ranges:     []rune{'a', 'z'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "SameLineString",
			pos:  position{line: 398, col: 1, offset: 8724},
			expr: &actionExpr{
				pos: position{line: 398, col: 19, offset: 8742},
				run: (*parser).callonSameLineString1,
				expr: &oneOrMoreExpr{
					pos: position{line: 398, col: 19, offset: 8742},
					expr: &charClassMatcher{
						pos:        position{line: 398, col: 19, offset: 8742},
						val:        "[^\\r\\n]",
						chars:      []rune{'\r', '\n'},
						ignoreCase: false,
						inverted:   true,
					},
				},
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 402, col: 1, offset: 8791},
			expr: &zeroOrMoreExpr{
				pos: position{line: 402, col: 19, offset: 8809},
				expr: &charClassMatcher{
					pos:        position{line: 402, col: 19, offset: 8809},
					val:        "[ \\t\\r\\n]",
					chars:      []rune{' ', '\t', '\r', '\n'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "Comma",
			pos:  position{line: 404, col: 1, offset: 8821},
			expr: &litMatcher{
				pos:        position{line: 404, col: 10, offset: 8830},
				val:        ",",
				ignoreCase: false,
				want:       "\",\"",
			},
		},
		{
			name: "EOF",
			pos:  position{line: 406, col: 1, offset: 8836},
			expr: &notExpr{
				pos: position{line: 406, col: 8, offset: 8843},
				expr: &anyMatcher{
					line: 406, col: 9, offset: 8844,
				},
			},
		},
	},
}

func (c *current) onInput1(conf any) (any, error) {
	cs := conf.([]interface{})

	var set Set
	for _, i := range cs {
		con := i.(Conformance)
		set = append(set, con)
	}
	return set, nil
}

func (p *parser) callonInput1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInput1(stack["conf"])
}

func (c *current) onConformance2(i, choice any) (any, error) {
	exp := i.(Expression)
	o := &Optional{Expression: exp}
	if choice != nil {
		o.Choice = choice.(*Choice)
	}
	return o, nil
}

func (p *parser) callonConformance2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConformance2(stack["i"], stack["choice"])
}

func (c *current) onConformance12() (any, error) {
	return &Mandatory{}, nil
}

func (p *parser) callonConformance12() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConformance12()
}

func (c *current) onConformance16(choice any) (any, error) {
	o := &Optional{}
	if choice != nil {
		o.Choice = choice.(*Choice)
	}
	return o, nil
}

func (p *parser) callonConformance16() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConformance16(stack["choice"])
}

func (c *current) onConformance23() (any, error) {
	return &Provisional{}, nil
}

func (p *parser) callonConformance23() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConformance23()
}

func (c *current) onConformance27() (any, error) {
	return &Deprecated{}, nil
}

func (p *parser) callonConformance27() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConformance27()
}

func (c *current) onConformance31() (any, error) {
	return &Disallowed{}, nil
}

func (p *parser) callonConformance31() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConformance31()
}

func (c *current) onConformance35() (any, error) {

	return &Described{}, nil
}

func (p *parser) callonConformance35() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConformance35()
}

func (c *current) onConformance39(eq any) (any, error) {
	exp := eq.(Expression)
	return &Mandatory{Expression: exp}, nil
}

func (p *parser) callonConformance39() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConformance39(stack["eq"])
}

func (c *current) onConformance44(eq any) (any, error) {
	exp := eq.(Expression)
	return &Mandatory{Expression: exp}, nil
}

func (p *parser) callonConformance44() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConformance44(stack["eq"])
}

func (c *current) onEquality1(left, right any) (any, error) {
	if right == nil {
		return left, nil
	}
	equalityOps := right.([]interface{})
	if len(equalityOps) == 0 {
		return left, nil
	}
	leftCE := left.(Expression)
	var ee *EqualityExpression
	for _, equalityOp := range equalityOps {
		ee = equalityOp.(*EqualityExpression)
		ee.Left = leftCE
		leftCE = ee
	}
	return ee, nil
}

func (p *parser) callonEquality1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEquality1(stack["left"], stack["right"])
}

func (c *current) onEqualsOp1(equals, f any) (any, error) {
	fc := f.(Expression)
	return &EqualityExpression{
		Not:   (string(equals.([]uint8)) == "!="),
		Right: fc,
	}, nil
}

func (p *parser) callonEqualsOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEqualsOp1(stack["equals"], stack["f"])
}

func (c *current) onLogicalTerm2(not, eq any) (any, error) {
	if not != nil {
		switch eq := eq.(type) {
		case *EqualityExpression:
			eq.Not = true
		case *LogicalExpression:
			eq.Not = true
		}
	}
	return eq, nil
}

func (p *parser) callonLogicalTerm2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLogicalTerm2(stack["not"], stack["eq"])
}

func (c *current) onLogicalTerm13(feature any) (any, error) {
	return feature, nil
}

func (p *parser) callonLogicalTerm13() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLogicalTerm13(stack["feature"])
}

func (c *current) onLogicalTerm16(reference any) (any, error) {
	return reference, nil
}

func (p *parser) callonLogicalTerm16() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLogicalTerm16(stack["reference"])
}

func (c *current) onLogicalTerm19(identifier any) (any, error) {
	return identifier, nil
}

func (p *parser) callonLogicalTerm19() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLogicalTerm19(stack["identifier"])
}

func (c *current) onOr1(left, right any) (any, error) {
	if right == nil {
		return left, nil
	}
	orOps := right.([]any)
	if len(orOps) == 0 {
		return left, nil
	}
	leftCE := left.(Expression)
	return NewLogicalExpression("|", leftCE, orOps)
}

func (p *parser) callonOr1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOr1(stack["left"], stack["right"])
}

func (c *current) onOrOp1(f any) (any, error) {
	fc := f.(Expression)
	return fc, nil
}

func (p *parser) callonOrOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrOp1(stack["f"])
}

func (c *current) onXor1(left, right any) (any, error) {
	if right == nil {
		return left, nil
	}
	xorOps := right.([]any)
	if len(xorOps) == 0 {
		return left, nil
	}
	leftCE := left.(Expression)
	return NewLogicalExpression("^", leftCE, xorOps)
}

func (p *parser) callonXor1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onXor1(stack["left"], stack["right"])
}

func (c *current) onXorOp1(f any) (any, error) {
	fc := f.(Expression)
	return fc, nil
}

func (p *parser) callonXorOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onXorOp1(stack["f"])
}

func (c *current) onAnd1(left, right any) (any, error) {
	if right == nil {
		return left, nil
	}
	addOps := right.([]any)
	if len(addOps) == 0 {
		return left, nil
	}
	leftCE := left.(Expression)
	return NewLogicalExpression("&", leftCE, addOps)
}

func (p *parser) callonAnd1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAnd1(stack["left"], stack["right"])
}

func (c *current) onAndOp1(f any) (any, error) {
	fc := f.(Expression)
	return fc, nil
}

func (p *parser) callonAndOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAndOp1(stack["f"])
}

func (c *current) onFloat1() (any, error) {
	return decimal.NewFromString(string(c.text))
}

func (p *parser) callonFloat1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFloat1()
}

func (c *current) onInteger1(sign, digits any) (any, error) {
	return strconv.ParseInt(string(c.text), 10, 64)
}

func (p *parser) callonInteger1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInteger1(stack["sign"], stack["digits"])
}

func (c *current) onHex1(hex any) (any, error) {
	var val []uint8
	for _, d := range hex.([]interface{}) {
		val = append(val, d.([]uint8)...)
	}
	return strconv.ParseUint(string(val), 16, 64)
}

func (p *parser) callonHex1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onHex1(stack["hex"])
}

func (c *current) onDigits1() (any, error) {
	return strconv.ParseInt(string(c.text), 10, 64)
}

func (p *parser) callonDigits1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDigits1()
}

func (c *current) onOperator2() (any, error) {
	return ComparisonOperatorLessThan, nil
}

func (p *parser) callonOperator2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOperator2()
}

func (c *current) onOperator4() (any, error) {
	return ComparisonOperatorLessThanOrEqual, nil
}

func (p *parser) callonOperator4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOperator4()
}

func (c *current) onOperator6() (any, error) {
	return ComparisonOperatorGreaterThan, nil
}

func (p *parser) callonOperator6() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOperator6()
}

func (c *current) onOperator8() (any, error) {
	return ComparisonOperatorGreaterThanOrEqual, nil
}

func (p *parser) callonOperator8() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOperator8()
}

func (c *current) onComparisonTerm2(feature any) (any, error) {
	return feature, nil
}

func (p *parser) callonComparisonTerm2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onComparisonTerm2(stack["feature"])
}

func (c *current) onComparisonTerm5(reference any) (any, error) {
	return reference, nil
}

func (p *parser) callonComparisonTerm5() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onComparisonTerm5(stack["reference"])
}

func (c *current) onComparisonTerm8(identifier any) (any, error) {
	return identifier, nil
}

func (p *parser) callonComparisonTerm8() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onComparisonTerm8(stack["identifier"])
}

func (c *current) onComparisonTerm11(number any) (any, error) {
	return number, nil
}

func (p *parser) callonComparisonTerm11() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onComparisonTerm11(stack["number"])
}

func (c *current) onComparison1(left, op, right any) (any, error) {

	leftVal := left.(ComparisonValue)
	rightVal := right.(ComparisonValue)
	return &ComparisonExpression{Left: leftVal, Right: rightVal, Op: op.(ComparisonOperator)}, nil
}

func (p *parser) callonComparison1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onComparison1(stack["left"], stack["op"], stack["right"])
}

func (c *current) onNumberValue2(val any) (any, error) {
	return NewHexValue(val.(uint64), string(c.text)), nil

}

func (p *parser) callonNumberValue2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumberValue2(stack["val"])
}

func (c *current) onNumberValue5(val any) (any, error) {
	return NewFloatValue(val.(decimal.Decimal), string(c.text)), nil

}

func (p *parser) callonNumberValue5() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumberValue5(stack["val"])
}

func (c *current) onNumberValue8(val any) (any, error) {
	return NewIntValue(val.(int64), string(c.text)), nil

}

func (p *parser) callonNumberValue8() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumberValue8(stack["val"])
}

func (c *current) onIdentifierOp1(not, identifier any) (any, error) {
	id := identifier.(string)
	ic := &IdentifierExpression{ID: id}
	if not != nil {
		ic.Not = true
	}
	return ic, nil
}

func (p *parser) callonIdentifierOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentifierOp1(stack["not"], stack["identifier"])
}

func (c *current) onIdentifierValue1(identifier any) (any, error) {

	id := identifier.(string)
	return &IdentifierValue{ID: id}, nil
}

func (p *parser) callonIdentifierValue1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentifierValue1(stack["identifier"])
}

func (c *current) onIdentifier1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonIdentifier1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentifier1()
}

func (c *current) onReferenceOp1(not, reference, label any) (any, error) {
	ic := &ReferenceExpression{Reference: reference.(string)}
	if label != nil {
		ic.Label = label.(string)
	}
	if not != nil {
		ic.Not = true
	}
	return ic, nil
}

func (p *parser) callonReferenceOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onReferenceOp1(stack["not"], stack["reference"], stack["label"])
}

func (c *current) onReferenceValue1(reference, label any) (any, error) {
	ic := &ReferenceValue{Reference: reference.(string)}
	if label != nil {
		ic.Label = label.(string)
	}
	return ic, nil
}

func (p *parser) callonReferenceValue1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onReferenceValue1(stack["reference"], stack["label"])
}

func (c *current) onReferenceLabel1(label any) (any, error) {
	return label.(string), nil
}

func (p *parser) callonReferenceLabel1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onReferenceLabel1(stack["label"])
}

func (c *current) onReferenceText1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonReferenceText1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onReferenceText1()
}

func (c *current) onReferenceId1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonReferenceId1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onReferenceId1()
}

func (c *current) onFeatureOp1(not, feature any) (any, error) {
	id := feature.(string)
	switch id {
	case "O", "M", "P":
		return nil, fmt.Errorf("invalid optional conformance value: %s", id)
	}
	ic := &FeatureExpression{Feature: id}
	if not != nil {
		ic.Not = true
	}
	return ic, nil
}

func (p *parser) callonFeatureOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFeatureOp1(stack["not"], stack["feature"])
}

func (c *current) onFeatureValue1(feature any) (any, error) {
	id := feature.(string)
	switch id {
	case "O", "M", "P":
		return nil, fmt.Errorf("invalid optional conformance value: %s", id)
	}
	ic := &FeatureValue{Feature: id}
	return ic, nil
}

func (p *parser) callonFeatureValue1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFeatureValue1(stack["feature"])
}

func (c *current) onFeature1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonFeature1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFeature1()
}

func (c *current) onChoiceRange1(lower, upper any) (any, error) {
	minVal := lower.(int)
	if minVal <= 0 {
		return nil, fmt.Errorf("invalid minimum: %d", minVal)
	}
	maxVal := upper.(int)
	if maxVal <= 0 && minVal > maxVal {
		return nil, fmt.Errorf("invalid maximum: %d", maxVal)
	}
	return &ChoiceRangeLimit{Min: minVal, Max: maxVal}, nil
}

func (p *parser) callonChoiceRange1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onChoiceRange1(stack["lower"], stack["upper"])
}

func (c *current) onChoiceMin1(limit any) (any, error) {
	if limit == nil {
		return &ChoiceMinLimit{Min: 1}, nil
	}
	minVal := limit.(int)
	if minVal <= 0 {
		return nil, fmt.Errorf("invalid minimum: %d", minVal)
	}
	return &ChoiceMinLimit{Min: minVal}, nil
}

func (p *parser) callonChoiceMin1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onChoiceMin1(stack["limit"])
}

func (c *current) onChoiceMax1(limit any) (any, error) {
	if limit == nil {
		return &ChoiceMaxLimit{Max: 1}, nil
	}
	maxVal := limit.(int)
	if maxVal <= 0 {
		return nil, fmt.Errorf("invalid maximum: %d", maxVal)
	}
	return &ChoiceMaxLimit{Max: maxVal}, nil
}

func (p *parser) callonChoiceMax1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onChoiceMax1(stack["limit"])
}

func (c *current) onChoiceExact1(limit any) (any, error) {
	exact := limit.(int)
	if exact <= 0 {
		return nil, fmt.Errorf("invalid exact: %d", exact)
	}
	return &ChoiceExactLimit{Limit: exact}, nil
}

func (p *parser) callonChoiceExact1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onChoiceExact1(stack["limit"])
}

func (c *current) onChoiceLimit1(limit any) (any, error) {
	return limit.(ChoiceLimit), nil
}

func (p *parser) callonChoiceLimit1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onChoiceLimit1(stack["limit"])
}

func (c *current) onSet1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonSet1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSet1()
}

func (c *current) onChoice1(set, limit any) (any, error) {
	choice := &Choice{Set: set.(string)}
	if limit != nil {
		switch v := limit.(type) {
		case ChoiceLimit:
			choice.Limit = v
		default:
			return nil, fmt.Errorf("unexpected choice limit type: %T", limit)
		}
	}
	return choice, nil
}

func (p *parser) callonChoice1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onChoice1(stack["set"], stack["limit"])
}

func (c *current) onPascalCase1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonPascalCase1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPascalCase1()
}

func (c *current) onCapitalized1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonCapitalized1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCapitalized1()
}

func (c *current) onUppercase1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonUppercase1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUppercase1()
}

func (c *current) onLowercase1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonLowercase1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLowercase1()
}

func (c *current) onSameLineString1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonSameLineString1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSameLineString1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
	parser *parser
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos    position
	offset int
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	//basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)
	p.cur.parser = p

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool

	// rules table, maps the rule offset to the rule node
	rules []*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
	offset position
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.rules = g.rules

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	var startRule *rule
	for _, r := range p.rules {
		if r.name == p.entrypoint {
			startRule = r
			break
		}
	}
	if startRule == nil {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	var ok bool
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	var (
		val any
		ok  bool
	)

	val, ok = p.parseRule(rule)

	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	val, ok := p.parseExpr(expr)

	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}

		val = actVal
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	pt := p.pt
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			return val, ok
		}
	}
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	pt := p.pt
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if ref.offset > len(p.rules)-1 {
		panic(fmt.Sprintf("%s: invalid rule: out of range", ref.pos))
	}

	rule := p.rules[ref.offset]
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	var vals []any

	pt := p.pt
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
