// Code generated by pigeon; DO NOT EDIT.

package conformance

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

func debug(format string, a ...any) (n int, err error) {
	return
	//return fmt.Fprintf(os.Stdout, format, a...)
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Input",
			pos:  position{line: 18, col: 1, offset: 223},
			expr: &actionExpr{
				pos: position{line: 18, col: 10, offset: 232},
				run: (*parser).callonInput1,
				expr: &seqExpr{
					pos: position{line: 18, col: 10, offset: 232},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 18, col: 10, offset: 232},
							label: "conf",
							expr: &oneOrMoreExpr{
								pos: position{line: 18, col: 15, offset: 237},
								expr: &ruleRefExpr{
									pos:    position{line: 18, col: 15, offset: 237},
									offset: 2,
								},
							},
						},
						&ruleRefExpr{
							pos:    position{line: 18, col: 28, offset: 250},
							offset: 35,
						},
					},
				},
			},
		},
		{
			name: "ConformanceSeparator",
			pos:  position{line: 29, col: 1, offset: 422},
			expr: &choiceExpr{
				pos: position{line: 29, col: 25, offset: 446},
				alternatives: []any{
					&seqExpr{
						pos: position{line: 29, col: 26, offset: 447},
						exprs: []any{
							&ruleRefExpr{
								pos:    position{line: 29, col: 26, offset: 447},
								offset: 33,
							},
							&ruleRefExpr{
								pos:    position{line: 29, col: 28, offset: 449},
								offset: 34,
							},
							&ruleRefExpr{
								pos:    position{line: 29, col: 34, offset: 455},
								offset: 33,
							},
						},
					},
					&andExpr{
						pos: position{line: 29, col: 39, offset: 460},
						expr: &ruleRefExpr{
							pos:    position{line: 29, col: 40, offset: 461},
							offset: 35,
						},
					},
				},
			},
		},
		{
			name: "Conformance",
			pos:  position{line: 31, col: 1, offset: 466},
			expr: &choiceExpr{
				pos: position{line: 31, col: 16, offset: 481},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 31, col: 16, offset: 481},
						run: (*parser).callonConformance2,
						expr: &seqExpr{
							pos: position{line: 31, col: 16, offset: 481},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 31, col: 16, offset: 481},
									val:        "[",
									ignoreCase: false,
									want:       "\"[\"",
								},
								&labeledExpr{
									pos:   position{line: 31, col: 20, offset: 485},
									label: "i",
									expr: &ruleRefExpr{
										pos:    position{line: 31, col: 22, offset: 487},
										offset: 3,
									},
								},
								&litMatcher{
									pos:        position{line: 31, col: 31, offset: 496},
									val:        "]",
									ignoreCase: false,
									want:       "\"]\"",
								},
								&labeledExpr{
									pos:   position{line: 31, col: 35, offset: 500},
									label: "choice",
									expr: &zeroOrOneExpr{
										pos: position{line: 31, col: 42, offset: 507},
										expr: &ruleRefExpr{
											pos:    position{line: 31, col: 42, offset: 507},
											offset: 26,
										},
									},
								},
								&ruleRefExpr{
									pos:    position{line: 31, col: 50, offset: 515},
									offset: 1,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 38, col: 6, offset: 690},
						run: (*parser).callonConformance12,
						expr: &seqExpr{
							pos: position{line: 38, col: 6, offset: 690},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 38, col: 6, offset: 690},
									val:        "M",
									ignoreCase: false,
									want:       "\"M\"",
								},
								&ruleRefExpr{
									pos:    position{line: 38, col: 11, offset: 695},
									offset: 1,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 40, col: 5, offset: 751},
						run: (*parser).callonConformance16,
						expr: &seqExpr{
							pos: position{line: 40, col: 5, offset: 751},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 40, col: 5, offset: 751},
									val:        "O",
									ignoreCase: false,
									want:       "\"O\"",
								},
								&labeledExpr{
									pos:   position{line: 40, col: 9, offset: 755},
									label: "choice",
									expr: &zeroOrOneExpr{
										pos: position{line: 40, col: 16, offset: 762},
										expr: &ruleRefExpr{
											pos:    position{line: 40, col: 16, offset: 762},
											offset: 26,
										},
									},
								},
								&ruleRefExpr{
									pos:    position{line: 40, col: 25, offset: 771},
									offset: 1,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 46, col: 5, offset: 902},
						run: (*parser).callonConformance23,
						expr: &seqExpr{
							pos: position{line: 46, col: 5, offset: 902},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 46, col: 5, offset: 902},
									val:        "P",
									ignoreCase: false,
									want:       "\"P\"",
								},
								&ruleRefExpr{
									pos:    position{line: 46, col: 10, offset: 907},
									offset: 1,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 48, col: 5, offset: 969},
						run: (*parser).callonConformance27,
						expr: &seqExpr{
							pos: position{line: 48, col: 5, offset: 969},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 48, col: 5, offset: 969},
									val:        "D",
									ignoreCase: false,
									want:       "\"D\"",
								},
								&ruleRefExpr{
									pos:    position{line: 48, col: 10, offset: 974},
									offset: 1,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 50, col: 5, offset: 1031},
						run: (*parser).callonConformance31,
						expr: &seqExpr{
							pos: position{line: 50, col: 5, offset: 1031},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 50, col: 5, offset: 1031},
									val:        "X",
									ignoreCase: false,
									want:       "\"X\"",
								},
								&ruleRefExpr{
									pos:    position{line: 50, col: 10, offset: 1036},
									offset: 1,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 52, col: 5, offset: 1093},
						run: (*parser).callonConformance35,
						expr: &seqExpr{
							pos: position{line: 52, col: 5, offset: 1093},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 52, col: 5, offset: 1093},
									val:        "desc",
									ignoreCase: false,
									want:       "\"desc\"",
								},
								&ruleRefExpr{
									pos:    position{line: 52, col: 13, offset: 1101},
									offset: 1,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 54, col: 5, offset: 1159},
						run: (*parser).callonConformance39,
						expr: &seqExpr{
							pos: position{line: 54, col: 5, offset: 1159},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 54, col: 5, offset: 1159},
									label: "eq",
									expr: &ruleRefExpr{
										pos:    position{line: 54, col: 8, offset: 1162},
										offset: 3,
									},
								},
								&ruleRefExpr{
									pos:    position{line: 54, col: 17, offset: 1171},
									offset: 1,
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Equality",
			pos:  position{line: 66, col: 1, offset: 1274},
			expr: &actionExpr{
				pos: position{line: 66, col: 13, offset: 1286},
				run: (*parser).callonEquality1,
				expr: &seqExpr{
					pos: position{line: 66, col: 13, offset: 1286},
					exprs: []any{
						&ruleRefExpr{
							pos:    position{line: 66, col: 13, offset: 1286},
							offset: 33,
						},
						&labeledExpr{
							pos:   position{line: 66, col: 15, offset: 1288},
							label: "left",
							expr: &ruleRefExpr{
								pos:    position{line: 66, col: 20, offset: 1293},
								offset: 5,
							},
						},
						&labeledExpr{
							pos:   position{line: 66, col: 23, offset: 1296},
							label: "right",
							expr: &zeroOrMoreExpr{
								pos: position{line: 66, col: 29, offset: 1302},
								expr: &ruleRefExpr{
									pos:    position{line: 66, col: 29, offset: 1302},
									offset: 4,
								},
							},
						},
						&ruleRefExpr{
							pos:    position{line: 66, col: 39, offset: 1312},
							offset: 33,
						},
					},
				},
			},
		},
		{
			name: "EqualsOp",
			pos:  position{line: 84, col: 1, offset: 1705},
			expr: &actionExpr{
				pos: position{line: 84, col: 13, offset: 1717},
				run: (*parser).callonEqualsOp1,
				expr: &seqExpr{
					pos: position{line: 84, col: 13, offset: 1717},
					exprs: []any{
						&ruleRefExpr{
							pos:    position{line: 84, col: 13, offset: 1717},
							offset: 33,
						},
						&labeledExpr{
							pos:   position{line: 84, col: 15, offset: 1719},
							label: "equals",
							expr: &choiceExpr{
								pos: position{line: 84, col: 23, offset: 1727},
								alternatives: []any{
									&litMatcher{
										pos:        position{line: 84, col: 23, offset: 1727},
										val:        "==",
										ignoreCase: false,
										want:       "\"==\"",
									},
									&litMatcher{
										pos:        position{line: 84, col: 28, offset: 1732},
										val:        "!=",
										ignoreCase: false,
										want:       "\"!=\"",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:    position{line: 84, col: 34, offset: 1738},
							offset: 33,
						},
						&labeledExpr{
							pos:   position{line: 84, col: 36, offset: 1740},
							label: "f",
							expr: &ruleRefExpr{
								pos:    position{line: 84, col: 38, offset: 1742},
								offset: 5,
							},
						},
					},
				},
			},
		},
		{
			name: "Or",
			pos:  position{line: 92, col: 1, offset: 1889},
			expr: &actionExpr{
				pos: position{line: 92, col: 7, offset: 1895},
				run: (*parser).callonOr1,
				expr: &seqExpr{
					pos: position{line: 92, col: 7, offset: 1895},
					exprs: []any{
						&ruleRefExpr{
							pos:    position{line: 92, col: 7, offset: 1895},
							offset: 33,
						},
						&labeledExpr{
							pos:   position{line: 92, col: 9, offset: 1897},
							label: "left",
							expr: &ruleRefExpr{
								pos:    position{line: 92, col: 14, offset: 1902},
								offset: 7,
							},
						},
						&ruleRefExpr{
							pos:    position{line: 92, col: 18, offset: 1906},
							offset: 33,
						},
						&labeledExpr{
							pos:   position{line: 92, col: 20, offset: 1908},
							label: "right",
							expr: &zeroOrMoreExpr{
								pos: position{line: 92, col: 26, offset: 1914},
								expr: &ruleRefExpr{
									pos:    position{line: 92, col: 26, offset: 1914},
									offset: 6,
								},
							},
						},
						&ruleRefExpr{
							pos:    position{line: 92, col: 32, offset: 1920},
							offset: 33,
						},
					},
				},
			},
		},
		{
			name: "OrOp",
			pos:  position{line: 104, col: 1, offset: 2151},
			expr: &actionExpr{
				pos: position{line: 104, col: 9, offset: 2159},
				run: (*parser).callonOrOp1,
				expr: &seqExpr{
					pos: position{line: 104, col: 9, offset: 2159},
					exprs: []any{
						&ruleRefExpr{
							pos:    position{line: 104, col: 9, offset: 2159},
							offset: 33,
						},
						&litMatcher{
							pos:        position{line: 104, col: 11, offset: 2161},
							val:        "|",
							ignoreCase: false,
							want:       "\"|\"",
						},
						&ruleRefExpr{
							pos:    position{line: 104, col: 15, offset: 2165},
							offset: 33,
						},
						&labeledExpr{
							pos:   position{line: 104, col: 17, offset: 2167},
							label: "f",
							expr: &ruleRefExpr{
								pos:    position{line: 104, col: 19, offset: 2169},
								offset: 7,
							},
						},
					},
				},
			},
		},
		{
			name: "Xor",
			pos:  position{line: 109, col: 1, offset: 2226},
			expr: &actionExpr{
				pos: position{line: 109, col: 8, offset: 2233},
				run: (*parser).callonXor1,
				expr: &seqExpr{
					pos: position{line: 109, col: 8, offset: 2233},
					exprs: []any{
						&ruleRefExpr{
							pos:    position{line: 109, col: 8, offset: 2233},
							offset: 33,
						},
						&labeledExpr{
							pos:   position{line: 109, col: 10, offset: 2235},
							label: "left",
							expr: &ruleRefExpr{
								pos:    position{line: 109, col: 15, offset: 2240},
								offset: 9,
							},
						},
						&ruleRefExpr{
							pos:    position{line: 109, col: 19, offset: 2244},
							offset: 33,
						},
						&labeledExpr{
							pos:   position{line: 109, col: 21, offset: 2246},
							label: "right",
							expr: &zeroOrMoreExpr{
								pos: position{line: 109, col: 27, offset: 2252},
								expr: &ruleRefExpr{
									pos:    position{line: 109, col: 27, offset: 2252},
									offset: 8,
								},
							},
						},
						&ruleRefExpr{
							pos:    position{line: 109, col: 34, offset: 2259},
							offset: 33,
						},
					},
				},
			},
		},
		{
			name: "XorOp",
			pos:  position{line: 121, col: 1, offset: 2493},
			expr: &actionExpr{
				pos: position{line: 121, col: 10, offset: 2502},
				run: (*parser).callonXorOp1,
				expr: &seqExpr{
					pos: position{line: 121, col: 10, offset: 2502},
					exprs: []any{
						&ruleRefExpr{
							pos:    position{line: 121, col: 10, offset: 2502},
							offset: 33,
						},
						&litMatcher{
							pos:        position{line: 121, col: 12, offset: 2504},
							val:        "^",
							ignoreCase: false,
							want:       "\"^\"",
						},
						&ruleRefExpr{
							pos:    position{line: 121, col: 16, offset: 2508},
							offset: 33,
						},
						&labeledExpr{
							pos:   position{line: 121, col: 18, offset: 2510},
							label: "f",
							expr: &ruleRefExpr{
								pos:    position{line: 121, col: 20, offset: 2512},
								offset: 9,
							},
						},
					},
				},
			},
		},
		{
			name: "And",
			pos:  position{line: 126, col: 1, offset: 2568},
			expr: &actionExpr{
				pos: position{line: 126, col: 8, offset: 2575},
				run: (*parser).callonAnd1,
				expr: &seqExpr{
					pos: position{line: 126, col: 8, offset: 2575},
					exprs: []any{
						&ruleRefExpr{
							pos:    position{line: 126, col: 8, offset: 2575},
							offset: 33,
						},
						&labeledExpr{
							pos:   position{line: 126, col: 10, offset: 2577},
							label: "left",
							expr: &ruleRefExpr{
								pos:    position{line: 126, col: 15, offset: 2582},
								offset: 11,
							},
						},
						&ruleRefExpr{
							pos:    position{line: 126, col: 27, offset: 2594},
							offset: 33,
						},
						&labeledExpr{
							pos:   position{line: 126, col: 29, offset: 2596},
							label: "right",
							expr: &zeroOrMoreExpr{
								pos: position{line: 126, col: 35, offset: 2602},
								expr: &ruleRefExpr{
									pos:    position{line: 126, col: 35, offset: 2602},
									offset: 10,
								},
							},
						},
						&ruleRefExpr{
							pos:    position{line: 126, col: 42, offset: 2609},
							offset: 33,
						},
					},
				},
			},
		},
		{
			name: "AndOp",
			pos:  position{line: 138, col: 1, offset: 2842},
			expr: &actionExpr{
				pos: position{line: 138, col: 10, offset: 2851},
				run: (*parser).callonAndOp1,
				expr: &seqExpr{
					pos: position{line: 138, col: 10, offset: 2851},
					exprs: []any{
						&ruleRefExpr{
							pos:    position{line: 138, col: 10, offset: 2851},
							offset: 33,
						},
						&litMatcher{
							pos:        position{line: 138, col: 12, offset: 2853},
							val:        "&",
							ignoreCase: false,
							want:       "\"&\"",
						},
						&ruleRefExpr{
							pos:    position{line: 138, col: 16, offset: 2857},
							offset: 33,
						},
						&labeledExpr{
							pos:   position{line: 138, col: 18, offset: 2859},
							label: "f",
							expr: &ruleRefExpr{
								pos:    position{line: 138, col: 20, offset: 2861},
								offset: 11,
							},
						},
					},
				},
			},
		},
		{
			name: "FeatureTerm",
			pos:  position{line: 143, col: 1, offset: 2926},
			expr: &choiceExpr{
				pos: position{line: 143, col: 16, offset: 2941},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 143, col: 16, offset: 2941},
						run: (*parser).callonFeatureTerm2,
						expr: &seqExpr{
							pos: position{line: 143, col: 16, offset: 2941},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 143, col: 16, offset: 2941},
									label: "not",
									expr: &zeroOrOneExpr{
										pos: position{line: 143, col: 20, offset: 2945},
										expr: &litMatcher{
											pos:        position{line: 143, col: 20, offset: 2945},
											val:        "!",
											ignoreCase: false,
											want:       "\"!\"",
										},
									},
								},
								&litMatcher{
									pos:        position{line: 143, col: 25, offset: 2950},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&ruleRefExpr{
									pos:    position{line: 143, col: 29, offset: 2954},
									offset: 33,
								},
								&labeledExpr{
									pos:   position{line: 143, col: 32, offset: 2957},
									label: "eq",
									expr: &ruleRefExpr{
										pos:    position{line: 143, col: 35, offset: 2960},
										offset: 3,
									},
								},
								&ruleRefExpr{
									pos:    position{line: 143, col: 44, offset: 2969},
									offset: 33,
								},
								&litMatcher{
									pos:        position{line: 143, col: 46, offset: 2971},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 153, col: 5, offset: 3208},
						run: (*parser).callonFeatureTerm13,
						expr: &labeledExpr{
							pos:   position{line: 153, col: 5, offset: 3208},
							label: "feature",
							expr: &ruleRefExpr{
								pos:    position{line: 153, col: 13, offset: 3216},
								offset: 18,
							},
						},
					},
					&actionExpr{
						pos: position{line: 155, col: 5, offset: 3257},
						run: (*parser).callonFeatureTerm16,
						expr: &labeledExpr{
							pos:   position{line: 155, col: 5, offset: 3257},
							label: "reference",
							expr: &ruleRefExpr{
								pos:    position{line: 155, col: 15, offset: 3267},
								offset: 14,
							},
						},
					},
					&actionExpr{
						pos: position{line: 157, col: 5, offset: 3312},
						run: (*parser).callonFeatureTerm19,
						expr: &labeledExpr{
							pos:   position{line: 157, col: 5, offset: 3312},
							label: "identifier",
							expr: &ruleRefExpr{
								pos:    position{line: 157, col: 16, offset: 3323},
								offset: 12,
							},
						},
					},
				},
			},
		},
		{
			name: "IdentifierOp",
			pos:  position{line: 163, col: 1, offset: 3372},
			expr: &actionExpr{
				pos: position{line: 163, col: 17, offset: 3388},
				run: (*parser).callonIdentifierOp1,
				expr: &seqExpr{
					pos: position{line: 163, col: 17, offset: 3388},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 163, col: 17, offset: 3388},
							label: "not",
							expr: &zeroOrOneExpr{
								pos: position{line: 163, col: 21, offset: 3392},
								expr: &litMatcher{
									pos:        position{line: 163, col: 21, offset: 3392},
									val:        "!",
									ignoreCase: false,
									want:       "\"!\"",
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 163, col: 26, offset: 3397},
							label: "identifier",
							expr: &ruleRefExpr{
								pos:    position{line: 163, col: 37, offset: 3408},
								offset: 13,
							},
						},
					},
				},
			},
		},
		{
			name: "Identifier",
			pos:  position{line: 173, col: 1, offset: 3565},
			expr: &actionExpr{
				pos: position{line: 173, col: 15, offset: 3579},
				run: (*parser).callonIdentifier1,
				expr: &seqExpr{
					pos: position{line: 173, col: 15, offset: 3579},
					exprs: []any{
						&ruleRefExpr{
							pos:    position{line: 173, col: 15, offset: 3579},
							offset: 28,
						},
						&zeroOrMoreExpr{
							pos: position{line: 173, col: 26, offset: 3590},
							expr: &seqExpr{
								pos: position{line: 173, col: 27, offset: 3591},
								exprs: []any{
									&litMatcher{
										pos:        position{line: 173, col: 27, offset: 3591},
										val:        "-",
										ignoreCase: false,
										want:       "\"-\"",
									},
									&ruleRefExpr{
										pos:    position{line: 173, col: 31, offset: 3595},
										offset: 28,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ReferenceOp",
			pos:  position{line: 177, col: 1, offset: 3648},
			expr: &actionExpr{
				pos: position{line: 177, col: 16, offset: 3663},
				run: (*parser).callonReferenceOp1,
				expr: &seqExpr{
					pos: position{line: 177, col: 16, offset: 3663},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 177, col: 16, offset: 3663},
							label: "not",
							expr: &zeroOrOneExpr{
								pos: position{line: 177, col: 20, offset: 3667},
								expr: &litMatcher{
									pos:        position{line: 177, col: 20, offset: 3667},
									val:        "!",
									ignoreCase: false,
									want:       "\"!\"",
								},
							},
						},
						&litMatcher{
							pos:        position{line: 177, col: 25, offset: 3672},
							val:        "<<",
							ignoreCase: false,
							want:       "\"<<\"",
						},
						&labeledExpr{
							pos:   position{line: 177, col: 30, offset: 3677},
							label: "reference",
							expr: &ruleRefExpr{
								pos:    position{line: 177, col: 40, offset: 3687},
								offset: 17,
							},
						},
						&labeledExpr{
							pos:   position{line: 177, col: 52, offset: 3699},
							label: "label",
							expr: &zeroOrOneExpr{
								pos: position{line: 177, col: 58, offset: 3705},
								expr: &ruleRefExpr{
									pos:    position{line: 177, col: 59, offset: 3706},
									offset: 15,
								},
							},
						},
						&litMatcher{
							pos:        position{line: 177, col: 77, offset: 3724},
							val:        ">>",
							ignoreCase: false,
							want:       "\">>\"",
						},
					},
				},
			},
		},
		{
			name: "ReferenceLabel",
			pos:  position{line: 189, col: 1, offset: 3937},
			expr: &actionExpr{
				pos: position{line: 189, col: 19, offset: 3955},
				run: (*parser).callonReferenceLabel1,
				expr: &seqExpr{
					pos: position{line: 189, col: 19, offset: 3955},
					exprs: []any{
						&ruleRefExpr{
							pos:    position{line: 189, col: 19, offset: 3955},
							offset: 33,
						},
						&ruleRefExpr{
							pos:    position{line: 189, col: 21, offset: 3957},
							offset: 34,
						},
						&ruleRefExpr{
							pos:    position{line: 189, col: 27, offset: 3963},
							offset: 33,
						},
						&labeledExpr{
							pos:   position{line: 189, col: 29, offset: 3965},
							label: "label",
							expr: &ruleRefExpr{
								pos:    position{line: 189, col: 35, offset: 3971},
								offset: 16,
							},
						},
						&andExpr{
							pos: position{line: 189, col: 50, offset: 3986},
							expr: &litMatcher{
								pos:        position{line: 189, col: 51, offset: 3987},
								val:        ">>",
								ignoreCase: false,
								want:       "\">>\"",
							},
						},
					},
				},
			},
		},
		{
			name: "ReferenceText",
			pos:  position{line: 193, col: 1, offset: 4032},
			expr: &actionExpr{
				pos: position{line: 193, col: 18, offset: 4049},
				run: (*parser).callonReferenceText1,
				expr: &oneOrMoreExpr{
					pos: position{line: 193, col: 18, offset: 4049},
					expr: &seqExpr{
						pos: position{line: 193, col: 19, offset: 4050},
						exprs: []any{
							&notExpr{
								pos: position{line: 193, col: 19, offset: 4050},
								expr: &litMatcher{
									pos:        position{line: 193, col: 20, offset: 4051},
									val:        ">>",
									ignoreCase: false,
									want:       "\">>\"",
								},
							},
							&anyMatcher{
								line: 193, col: 25, offset: 4056,
							},
						},
					},
				},
			},
		},
		{
			name: "ReferenceId",
			pos:  position{line: 197, col: 1, offset: 4101},
			expr: &actionExpr{
				pos: position{line: 197, col: 16, offset: 4116},
				run: (*parser).callonReferenceId1,
				expr: &seqExpr{
					pos: position{line: 197, col: 16, offset: 4116},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 197, col: 16, offset: 4116},
							val:        "ref_",
							ignoreCase: false,
							want:       "\"ref_\"",
						},
						&ruleRefExpr{
							pos:    position{line: 197, col: 23, offset: 4123},
							offset: 28,
						},
					},
				},
			},
		},
		{
			name: "FeatureOp",
			pos:  position{line: 201, col: 1, offset: 4174},
			expr: &actionExpr{
				pos: position{line: 201, col: 14, offset: 4187},
				run: (*parser).callonFeatureOp1,
				expr: &seqExpr{
					pos: position{line: 201, col: 14, offset: 4187},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 201, col: 14, offset: 4187},
							label: "not",
							expr: &zeroOrOneExpr{
								pos: position{line: 201, col: 18, offset: 4191},
								expr: &litMatcher{
									pos:        position{line: 201, col: 18, offset: 4191},
									val:        "!",
									ignoreCase: false,
									want:       "\"!\"",
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 201, col: 23, offset: 4196},
							label: "feature",
							expr: &ruleRefExpr{
								pos:    position{line: 201, col: 31, offset: 4204},
								offset: 19,
							},
						},
					},
				},
			},
		},
		{
			name: "Feature",
			pos:  position{line: 215, col: 1, offset: 4484},
			expr: &actionExpr{
				pos: position{line: 215, col: 12, offset: 4495},
				run: (*parser).callonFeature1,
				expr: &seqExpr{
					pos: position{line: 215, col: 12, offset: 4495},
					exprs: []any{
						&charClassMatcher{
							pos:        position{line: 215, col: 12, offset: 4495},
							val:        "[A-Z]",
							ranges:     []rune{'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
						&oneOrMoreExpr{
							pos: position{line: 215, col: 17, offset: 4500},
							expr: &charClassMatcher{
								pos:        position{line: 215, col: 17, offset: 4500},
								val:        "[A-Z0-9_]",
								chars:      []rune{'_'},
								ranges:     []rune{'A', 'Z', '0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&andExpr{
							pos: position{line: 215, col: 28, offset: 4511},
							expr: &choiceExpr{
								pos: position{line: 215, col: 30, offset: 4513},
								alternatives: []any{
									&notExpr{
										pos: position{line: 215, col: 30, offset: 4513},
										expr: &charClassMatcher{
											pos:        position{line: 215, col: 31, offset: 4514},
											val:        "[A-Za-z0-9_]",
											chars:      []rune{'_'},
											ranges:     []rune{'A', 'Z', 'a', 'z', '0', '9'},
											ignoreCase: false,
											inverted:   false,
										},
									},
									&ruleRefExpr{
										pos:    position{line: 215, col: 46, offset: 4529},
										offset: 35,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ChoiceRange",
			pos:  position{line: 223, col: 1, offset: 4574},
			expr: &actionExpr{
				pos: position{line: 223, col: 16, offset: 4589},
				run: (*parser).callonChoiceRange1,
				expr: &seqExpr{
					pos: position{line: 223, col: 16, offset: 4589},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 223, col: 16, offset: 4589},
							label: "lower",
							expr: &ruleRefExpr{
								pos:    position{line: 223, col: 22, offset: 4595},
								offset: 27,
							},
						},
						&litMatcher{
							pos:        position{line: 223, col: 30, offset: 4603},
							val:        "-",
							ignoreCase: false,
							want:       "\"-\"",
						},
						&labeledExpr{
							pos:   position{line: 223, col: 34, offset: 4607},
							label: "upper",
							expr: &ruleRefExpr{
								pos:    position{line: 223, col: 40, offset: 4613},
								offset: 27,
							},
						},
					},
				},
			},
		},
		{
			name: "ChoiceMin",
			pos:  position{line: 235, col: 1, offset: 4936},
			expr: &actionExpr{
				pos: position{line: 235, col: 14, offset: 4949},
				run: (*parser).callonChoiceMin1,
				expr: &seqExpr{
					pos: position{line: 235, col: 14, offset: 4949},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 235, col: 14, offset: 4949},
							label: "limit",
							expr: &zeroOrOneExpr{
								pos: position{line: 235, col: 20, offset: 4955},
								expr: &ruleRefExpr{
									pos:    position{line: 235, col: 20, offset: 4955},
									offset: 27,
								},
							},
						},
						&litMatcher{
							pos:        position{line: 235, col: 29, offset: 4964},
							val:        "+",
							ignoreCase: false,
							want:       "\"+\"",
						},
					},
				},
			},
		},
		{
			name: "ChoiceMax",
			pos:  position{line: 246, col: 1, offset: 5207},
			expr: &actionExpr{
				pos: position{line: 246, col: 14, offset: 5220},
				run: (*parser).callonChoiceMax1,
				expr: &seqExpr{
					pos: position{line: 246, col: 14, offset: 5220},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 246, col: 14, offset: 5220},
							label: "limit",
							expr: &zeroOrOneExpr{
								pos: position{line: 246, col: 20, offset: 5226},
								expr: &ruleRefExpr{
									pos:    position{line: 246, col: 20, offset: 5226},
									offset: 27,
								},
							},
						},
						&litMatcher{
							pos:        position{line: 246, col: 29, offset: 5235},
							val:        "-",
							ignoreCase: false,
							want:       "\"-\"",
						},
					},
				},
			},
		},
		{
			name: "ChoiceExact",
			pos:  position{line: 257, col: 1, offset: 5476},
			expr: &actionExpr{
				pos: position{line: 257, col: 16, offset: 5491},
				run: (*parser).callonChoiceExact1,
				expr: &labeledExpr{
					pos:   position{line: 257, col: 16, offset: 5491},
					label: "limit",
					expr: &ruleRefExpr{
						pos:    position{line: 257, col: 22, offset: 5497},
						offset: 27,
					},
				},
			},
		},
		{
			name: "ChoiceLimit",
			pos:  position{line: 265, col: 1, offset: 5668},
			expr: &actionExpr{
				pos: position{line: 265, col: 16, offset: 5683},
				run: (*parser).callonChoiceLimit1,
				expr: &labeledExpr{
					pos:   position{line: 265, col: 16, offset: 5683},
					label: "limit",
					expr: &choiceExpr{
						pos: position{line: 265, col: 23, offset: 5690},
						alternatives: []any{
							&ruleRefExpr{
								pos:    position{line: 265, col: 23, offset: 5690},
								offset: 20,
							},
							&ruleRefExpr{
								pos:    position{line: 265, col: 37, offset: 5704},
								offset: 21,
							},
							&ruleRefExpr{
								pos:    position{line: 265, col: 49, offset: 5716},
								offset: 22,
							},
							&ruleRefExpr{
								pos:    position{line: 265, col: 61, offset: 5728},
								offset: 23,
							},
						},
					},
				},
			},
		},
		{
			name: "Set",
			pos:  position{line: 269, col: 1, offset: 5782},
			expr: &actionExpr{
				pos: position{line: 269, col: 8, offset: 5789},
				run: (*parser).callonSet1,
				expr: &oneOrMoreExpr{
					pos: position{line: 269, col: 8, offset: 5789},
					expr: &charClassMatcher{
						pos:        position{line: 269, col: 8, offset: 5789},
						val:        "[a-z]",
						ranges:     []rune{'a', 'z'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "Choice",
			pos:  position{line: 273, col: 1, offset: 5832},
			expr: &actionExpr{
				pos: position{line: 273, col: 11, offset: 5842},
				run: (*parser).callonChoice1,
				expr: &seqExpr{
					pos: position{line: 273, col: 11, offset: 5842},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 273, col: 11, offset: 5842},
							val:        ".",
							ignoreCase: false,
							want:       "\".\"",
						},
						&labeledExpr{
							pos:   position{line: 273, col: 15, offset: 5846},
							label: "set",
							expr: &ruleRefExpr{
								pos:    position{line: 273, col: 19, offset: 5850},
								offset: 25,
							},
						},
						&labeledExpr{
							pos:   position{line: 273, col: 23, offset: 5854},
							label: "limit",
							expr: &zeroOrOneExpr{
								pos: position{line: 273, col: 29, offset: 5860},
								expr: &ruleRefExpr{
									pos:    position{line: 273, col: 29, offset: 5860},
									offset: 24,
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 290, col: 1, offset: 6176},
			expr: &actionExpr{
				pos: position{line: 290, col: 12, offset: 6187},
				run: (*parser).callonInteger1,
				expr: &oneOrMoreExpr{
					pos: position{line: 290, col: 13, offset: 6188},
					expr: &charClassMatcher{
						pos:        position{line: 290, col: 13, offset: 6188},
						val:        "[0-9]",
						ranges:     []rune{'0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "PascalCase",
			pos:  position{line: 294, col: 1, offset: 6249},
			expr: &actionExpr{
				pos: position{line: 294, col: 15, offset: 6263},
				run: (*parser).callonPascalCase1,
				expr: &seqExpr{
					pos: position{line: 294, col: 15, offset: 6263},
					exprs: []any{
						&oneOrMoreExpr{
							pos: position{line: 294, col: 15, offset: 6263},
							expr: &ruleRefExpr{
								pos:    position{line: 294, col: 15, offset: 6263},
								offset: 29,
							},
						},
						&zeroOrMoreExpr{
							pos: position{line: 294, col: 28, offset: 6276},
							expr: &ruleRefExpr{
								pos:    position{line: 294, col: 28, offset: 6276},
								offset: 29,
							},
						},
					},
				},
			},
		},
		{
			name: "Capitalized",
			pos:  position{line: 299, col: 1, offset: 6327},
			expr: &actionExpr{
				pos: position{line: 299, col: 16, offset: 6342},
				run: (*parser).callonCapitalized1,
				expr: &seqExpr{
					pos: position{line: 299, col: 16, offset: 6342},
					exprs: []any{
						&oneOrMoreExpr{
							pos: position{line: 299, col: 16, offset: 6342},
							expr: &ruleRefExpr{
								pos:    position{line: 299, col: 16, offset: 6342},
								offset: 30,
							},
						},
						&zeroOrMoreExpr{
							pos: position{line: 299, col: 27, offset: 6353},
							expr: &ruleRefExpr{
								pos:    position{line: 299, col: 27, offset: 6353},
								offset: 31,
							},
						},
					},
				},
			},
		},
		{
			name: "Uppercase",
			pos:  position{line: 303, col: 1, offset: 6401},
			expr: &actionExpr{
				pos: position{line: 303, col: 14, offset: 6414},
				run: (*parser).callonUppercase1,
				expr: &charClassMatcher{
					pos:        position{line: 303, col: 14, offset: 6414},
					val:        "[A-Z]",
					ranges:     []rune{'A', 'Z'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "Lowercase",
			pos:  position{line: 307, col: 1, offset: 6457},
			expr: &actionExpr{
				pos: position{line: 307, col: 14, offset: 6470},
				run: (*parser).callonLowercase1,
				expr: &charClassMatcher{
					pos:        position{line: 307, col: 14, offset: 6470},
					val:        "[a-z]",
					ranges:     []rune{'a', 'z'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "SameLineString",
			pos:  position{line: 311, col: 1, offset: 6513},
			expr: &actionExpr{
				pos: position{line: 311, col: 19, offset: 6531},
				run: (*parser).callonSameLineString1,
				expr: &oneOrMoreExpr{
					pos: position{line: 311, col: 19, offset: 6531},
					expr: &charClassMatcher{
						pos:        position{line: 311, col: 19, offset: 6531},
						val:        "[^\\n]",
						chars:      []rune{'\n'},
						ignoreCase: false,
						inverted:   true,
					},
				},
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 315, col: 1, offset: 6578},
			expr: &zeroOrMoreExpr{
				pos: position{line: 315, col: 19, offset: 6596},
				expr: &charClassMatcher{
					pos:        position{line: 315, col: 19, offset: 6596},
					val:        "[ \\t\\r\\n]",
					chars:      []rune{' ', '\t', '\r', '\n'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "Comma",
			pos:  position{line: 317, col: 1, offset: 6608},
			expr: &litMatcher{
				pos:        position{line: 317, col: 10, offset: 6617},
				val:        ",",
				ignoreCase: false,
				want:       "\",\"",
			},
		},
		{
			name: "EOF",
			pos:  position{line: 319, col: 1, offset: 6623},
			expr: &notExpr{
				pos: position{line: 319, col: 8, offset: 6630},
				expr: &anyMatcher{
					line: 319, col: 9, offset: 6631,
				},
			},
		},
	},
}

func (c *current) onInput1(conf any) (any, error) {
	cs := conf.([]interface{})

	var set Set
	for _, i := range cs {
		con := i.(Conformance)
		set = append(set, con)
	}
	return set, nil
}

func (p *parser) callonInput1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInput1(stack["conf"])
}

func (c *current) onConformance2(i, choice any) (any, error) {
	exp := i.(Expression)
	o := &Optional{Expression: exp}
	if choice != nil {
		o.Choice = choice.(*Choice)
	}
	return o, nil
}

func (p *parser) callonConformance2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConformance2(stack["i"], stack["choice"])
}

func (c *current) onConformance12() (any, error) {
	return &Mandatory{}, nil
}

func (p *parser) callonConformance12() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConformance12()
}

func (c *current) onConformance16(choice any) (any, error) {
	o := &Optional{}
	if choice != nil {
		o.Choice = choice.(*Choice)
	}
	return o, nil
}

func (p *parser) callonConformance16() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConformance16(stack["choice"])
}

func (c *current) onConformance23() (any, error) {
	return &Provisional{}, nil
}

func (p *parser) callonConformance23() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConformance23()
}

func (c *current) onConformance27() (any, error) {
	return &Deprecated{}, nil
}

func (p *parser) callonConformance27() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConformance27()
}

func (c *current) onConformance31() (any, error) {
	return &Disallowed{}, nil
}

func (p *parser) callonConformance31() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConformance31()
}

func (c *current) onConformance35() (any, error) {

	return &Described{}, nil
}

func (p *parser) callonConformance35() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConformance35()
}

func (c *current) onConformance39(eq any) (any, error) {
	exp := eq.(Expression)
	return &Mandatory{Expression: exp}, nil
}

func (p *parser) callonConformance39() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConformance39(stack["eq"])
}

func (c *current) onEquality1(left, right any) (any, error) {
	if right == nil {
		return left, nil
	}
	equalityOps := right.([]interface{})
	if len(equalityOps) == 0 {
		return left, nil
	}
	leftCE := left.(Expression)
	var ee *EqualityExpression
	for _, equalityOp := range equalityOps {
		ee = equalityOp.(*EqualityExpression)
		ee.Left = leftCE
		leftCE = ee
	}
	return ee, nil
}

func (p *parser) callonEquality1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEquality1(stack["left"], stack["right"])
}

func (c *current) onEqualsOp1(equals, f any) (any, error) {
	fc := f.(Expression)
	return &EqualityExpression{
		Not:   (string(equals.([]uint8)) == "!="),
		Right: fc,
	}, nil
}

func (p *parser) callonEqualsOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEqualsOp1(stack["equals"], stack["f"])
}

func (c *current) onOr1(left, right any) (any, error) {
	if right == nil {
		return left, nil
	}
	orOps := right.([]any)
	if len(orOps) == 0 {
		return left, nil
	}
	leftCE := left.(Expression)
	return NewLogicalExpression("|", leftCE, orOps)
}

func (p *parser) callonOr1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOr1(stack["left"], stack["right"])
}

func (c *current) onOrOp1(f any) (any, error) {
	fc := f.(Expression)
	return fc, nil
}

func (p *parser) callonOrOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrOp1(stack["f"])
}

func (c *current) onXor1(left, right any) (any, error) {
	if right == nil {
		return left, nil
	}
	xorOps := right.([]any)
	if len(xorOps) == 0 {
		return left, nil
	}
	leftCE := left.(Expression)
	return NewLogicalExpression("^", leftCE, xorOps)
}

func (p *parser) callonXor1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onXor1(stack["left"], stack["right"])
}

func (c *current) onXorOp1(f any) (any, error) {
	fc := f.(Expression)
	return fc, nil
}

func (p *parser) callonXorOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onXorOp1(stack["f"])
}

func (c *current) onAnd1(left, right any) (any, error) {
	if right == nil {
		return left, nil
	}
	addOps := right.([]any)
	if len(addOps) == 0 {
		return left, nil
	}
	leftCE := left.(Expression)
	return NewLogicalExpression("&", leftCE, addOps)
}

func (p *parser) callonAnd1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAnd1(stack["left"], stack["right"])
}

func (c *current) onAndOp1(f any) (any, error) {
	fc := f.(Expression)
	return fc, nil
}

func (p *parser) callonAndOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAndOp1(stack["f"])
}

func (c *current) onFeatureTerm2(not, eq any) (any, error) {
	if not != nil {
		switch eq := eq.(type) {
		case *EqualityExpression:
			eq.Not = true
		case *LogicalExpression:
			eq.Not = true
		}
	}
	return eq, nil
}

func (p *parser) callonFeatureTerm2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFeatureTerm2(stack["not"], stack["eq"])
}

func (c *current) onFeatureTerm13(feature any) (any, error) {
	return feature, nil
}

func (p *parser) callonFeatureTerm13() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFeatureTerm13(stack["feature"])
}

func (c *current) onFeatureTerm16(reference any) (any, error) {
	return reference, nil
}

func (p *parser) callonFeatureTerm16() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFeatureTerm16(stack["reference"])
}

func (c *current) onFeatureTerm19(identifier any) (any, error) {
	return identifier, nil
}

func (p *parser) callonFeatureTerm19() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFeatureTerm19(stack["identifier"])
}

func (c *current) onIdentifierOp1(not, identifier any) (any, error) {
	id := identifier.(string)
	ic := &IdentifierExpression{ID: id}
	if not != nil {
		ic.Not = true
	}
	return ic, nil
}

func (p *parser) callonIdentifierOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentifierOp1(stack["not"], stack["identifier"])
}

func (c *current) onIdentifier1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonIdentifier1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentifier1()
}

func (c *current) onReferenceOp1(not, reference, label any) (any, error) {
	ic := &ReferenceExpression{Reference: reference.(string)}
	if label != nil {
		ic.Label = label.(string)
	}
	if not != nil {
		ic.Not = true
	}
	return ic, nil
}

func (p *parser) callonReferenceOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onReferenceOp1(stack["not"], stack["reference"], stack["label"])
}

func (c *current) onReferenceLabel1(label any) (any, error) {
	return label.(string), nil
}

func (p *parser) callonReferenceLabel1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onReferenceLabel1(stack["label"])
}

func (c *current) onReferenceText1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonReferenceText1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onReferenceText1()
}

func (c *current) onReferenceId1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonReferenceId1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onReferenceId1()
}

func (c *current) onFeatureOp1(not, feature any) (any, error) {
	id := feature.(string)
	switch id {
	case "O", "M", "P":
		return nil, fmt.Errorf("invalid optional conformance value: %s", id)
	}
	ic := &FeatureExpression{Feature: id}
	if not != nil {
		ic.Not = true
	}
	return ic, nil
}

func (p *parser) callonFeatureOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFeatureOp1(stack["not"], stack["feature"])
}

func (c *current) onFeature1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonFeature1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFeature1()
}

func (c *current) onChoiceRange1(lower, upper any) (any, error) {
	minVal := lower.(int)
	if minVal <= 0 {
		return nil, fmt.Errorf("invalid minimum: %d", minVal)
	}
	maxVal := upper.(int)
	if maxVal <= 0 && minVal > maxVal {
		return nil, fmt.Errorf("invalid maximum: %d", maxVal)
	}
	return &ChoiceRangeLimit{Min: minVal, Max: maxVal}, nil
}

func (p *parser) callonChoiceRange1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onChoiceRange1(stack["lower"], stack["upper"])
}

func (c *current) onChoiceMin1(limit any) (any, error) {
	if limit == nil {
		return &ChoiceMinLimit{Min: 1}, nil
	}
	minVal := limit.(int)
	if minVal <= 0 {
		return nil, fmt.Errorf("invalid minimum: %d", minVal)
	}
	return &ChoiceMinLimit{Min: minVal}, nil
}

func (p *parser) callonChoiceMin1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onChoiceMin1(stack["limit"])
}

func (c *current) onChoiceMax1(limit any) (any, error) {
	if limit == nil {
		return &ChoiceMaxLimit{Max: 1}, nil
	}
	maxVal := limit.(int)
	if maxVal <= 0 {
		return nil, fmt.Errorf("invalid maximum: %d", maxVal)
	}
	return &ChoiceMaxLimit{Max: maxVal}, nil
}

func (p *parser) callonChoiceMax1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onChoiceMax1(stack["limit"])
}

func (c *current) onChoiceExact1(limit any) (any, error) {
	exact := limit.(int)
	if exact <= 0 {
		return nil, fmt.Errorf("invalid exact: %d", exact)
	}
	return &ChoiceExactLimit{Limit: exact}, nil
}

func (p *parser) callonChoiceExact1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onChoiceExact1(stack["limit"])
}

func (c *current) onChoiceLimit1(limit any) (any, error) {
	return limit.(ChoiceLimit), nil
}

func (p *parser) callonChoiceLimit1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onChoiceLimit1(stack["limit"])
}

func (c *current) onSet1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonSet1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSet1()
}

func (c *current) onChoice1(set, limit any) (any, error) {
	choice := &Choice{Set: set.(string)}
	if limit != nil {
		switch v := limit.(type) {
		case ChoiceLimit:
			choice.Limit = v
		default:
			return nil, fmt.Errorf("unexpected choice limit type: %T", limit)
		}
	}
	return choice, nil
}

func (p *parser) callonChoice1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onChoice1(stack["set"], stack["limit"])
}

func (c *current) onInteger1() (any, error) {
	return strconv.Atoi(string(c.text))

}

func (p *parser) callonInteger1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInteger1()
}

func (c *current) onPascalCase1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonPascalCase1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPascalCase1()
}

func (c *current) onCapitalized1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonCapitalized1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCapitalized1()
}

func (c *current) onUppercase1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonUppercase1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUppercase1()
}

func (c *current) onLowercase1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonLowercase1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLowercase1()
}

func (c *current) onSameLineString1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonSameLineString1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSameLineString1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
	parser *parser
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos    position
	offset int
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	//basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)
	p.cur.parser = p

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool

	// rules table, maps the rule offset to the rule node
	rules []*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
	offset position
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.rules = g.rules

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	var startRule *rule
	for _, r := range p.rules {
		if r.name == p.entrypoint {
			startRule = r
			break
		}
	}
	if startRule == nil {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	var ok bool
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	var (
		val any
		ok  bool
	)

	val, ok = p.parseRule(rule)

	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	val, ok := p.parseExpr(expr)

	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}

		val = actVal
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	pt := p.pt
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			return val, ok
		}
	}
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	pt := p.pt
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if ref.offset > len(p.rules)-1 {
		panic(fmt.Sprintf("%s: invalid rule: out of range", ref.pos))
	}

	rule := p.rules[ref.offset]
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	var vals []any

	pt := p.pt
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
