package zapdiff

import (
	"bufio"
	"fmt"
	"os"
	"regexp"
	"strings"
)

type xpathSegment struct {
	tag    string
	attr   string
	value  string
	isAttr bool // true for [@attr='val'], false for [tag='val']
}

var segmentRegex = regexp.MustCompile(`^([a-zA-Z0-9_-]+)(?:\[(@?)([a-zA-Z0-9_()-]+)='([^']*)'\])?$`) // This regex is generated by Gemini

func parseEntityUniqueIdentifier(id string) ([]xpathSegment, error) {
	parts := strings.Split(id, "/")
	var segments []xpathSegment
	for _, part := range parts {
		if part == "" {
			continue
		}
		matches := segmentRegex.FindStringSubmatch(part)
		if matches == nil {
			return nil, fmt.Errorf("invalid segment: %s", part)
		}
		seg := xpathSegment{tag: matches[1]}
		if len(matches) > 3 && matches[3] != "" {
			seg.isAttr = matches[2] == "@"
			seg.attr = matches[3]
			seg.value = matches[4]
		}
		segments = append(segments, seg)
	}
	return segments, nil
}

// findElementLines searches for the element identified by id in the file at path and returns its lines.
func findElementLines(path string, id string) ([]string, int, error) {
	segments, err := parseEntityUniqueIdentifier(id)
	if err != nil {
		return nil, 0, err
	}

	f, err := os.Open(path)
	if err != nil {
		return nil, 0, err
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	var allLines []string
	for scanner.Scan() {
		allLines = append(allLines, scanner.Text()+"\n")
	}
	if err := scanner.Err(); err != nil {
		return nil, 0, err
	}

	segIdx := 0
	foundParent := false
	parentStartLine := -1
	startLine := -1

	for i := 0; i < len(allLines); i++ {
		line := allLines[i]
		if segIdx >= len(segments) {
			break
		}
		seg := segments[segIdx]

		// Boundary check: if we are looking for a child segment, and we see the parent close tag, we fail!
		if segIdx > 0 {
			parentTag := segments[segIdx-1].tag
			if strings.Contains(line, "</"+parentTag+">") {
				return nil, 0, nil // Not found within parent boundary
			}
		}

		if seg.attr == "text()" {
			// Text content filter
			if strings.Contains(line, "<"+seg.tag) && strings.Contains(line, seg.value) {
				segIdx++
				if segIdx >= len(segments) {
					startLine = i
				}
			}
		} else if seg.attr != "" && !seg.isAttr {
			// Child element filter
			if !foundParent {
				if strings.Contains(line, "<"+seg.tag) {
					foundParent = true
					parentStartLine = i
				}
			}
			if foundParent {
				childRegex := fmt.Sprintf(`<%s(\s+[^>]*)?>%s</%s>`, regexp.QuoteMeta(seg.attr), regexp.QuoteMeta(seg.value), regexp.QuoteMeta(seg.attr))
				matched, _ := regexp.MatchString(childRegex, line)
				if matched {
					segIdx++
					foundParent = false
					if segIdx >= len(segments) {
						startLine = parentStartLine
					}
				}
			}
		} else {
			// Normal or attr filter
			if strings.Contains(line, "<"+seg.tag) {
				if seg.attr == "" {
					segIdx++
					if segIdx >= len(segments) {
						startLine = i
					}
				} else {
					attrStr1 := fmt.Sprintf(`%s="%s"`, seg.attr, seg.value)
					attrStr2 := fmt.Sprintf(`%s='%s'`, seg.attr, seg.value)
					if strings.Contains(line, attrStr1) || strings.Contains(line, attrStr2) {
						segIdx++
						if segIdx >= len(segments) {
							startLine = i
						}
					}
				}
			}
		}
	}

	if segIdx < len(segments) || startLine == -1 {
		return nil, 0, nil // Not found
	}

	targetTag := segments[len(segments)-1].tag

	isSelfClosing := false
	endLine := startLine
	for i := startLine; i < len(allLines); i++ {
		if strings.Contains(allLines[i], "/>") {
			isSelfClosing = true
			endLine = i
			break
		}
		if strings.Contains(allLines[i], ">") {
			break
		}
	}

	if isSelfClosing {
		return allLines[startLine : endLine+1], startLine + 1, nil
	}

	closeTag := "</" + targetTag + ">"
	for i := startLine; i < len(allLines); i++ {
		if strings.Contains(allLines[i], closeTag) {
			endLine = i
			break
		}
	}

	return allLines[startLine : endLine+1], startLine + 1, nil
}

// GenerateUnifiedDiff generates a block-based unified diff between two sets of lines using LCS.
func GenerateUnifiedDiff(lines1, lines2 []string, start1, start2 int) (string, error) {
	m := len(lines1)
	n := len(lines2)
	c := make([][]int, m+1)
	for i := range c {
		c[i] = make([]int, n+1)
	}

	for i := 1; i <= m; i++ {
		for j := 1; j <= n; j++ {
			if lines1[i-1] == lines2[j-1] {
				c[i][j] = c[i-1][j-1] + 1
			} else {
				c[i][j] = max(c[i-1][j], c[i][j-1])
			}
		}
	}

	type edit struct {
		op   rune // ' ', '-', '+'
		line string
	}
	var edits []edit

	var collectDiff func(i, j int)
	collectDiff = func(i, j int) {
		if i > 0 && j > 0 && lines1[i-1] == lines2[j-1] {
			collectDiff(i-1, j-1)
			edits = append(edits, edit{op: ' ', line: lines1[i-1]})
		} else if j > 0 && (i == 0 || c[i][j-1] >= c[i-1][j]) {
			collectDiff(i, j-1)
			edits = append(edits, edit{op: '+', line: lines2[j-1]})
		} else if i > 0 && (j == 0 || c[i][j-1] < c[i-1][j]) {
			collectDiff(i-1, j)
			edits = append(edits, edit{op: '-', line: lines1[i-1]})
		}
	}
	collectDiff(m, n)

	var result strings.Builder
	result.WriteString("--- Ref\n")
	result.WriteString("+++ Generated\n")
	result.WriteString(fmt.Sprintf("@@ -%d,%d +%d,%d @@\n", start1, m, start2, n))

	idx := 0
	for idx < len(edits) {
		if edits[idx].op == ' ' {
			result.WriteString(" " + edits[idx].line)
			idx++
		} else {
			j := idx
			for j < len(edits) && edits[j].op != ' ' {
				j++
			}
			for k := idx; k < j; k++ {
				if edits[k].op == '-' {
					result.WriteString("-" + edits[k].line)
				}
			}
			for k := idx; k < j; k++ {
				if edits[k].op == '+' {
					result.WriteString("+" + edits[k].line)
				}
			}
			idx = j
		}
	}
	return result.String(), nil
}

func max(a, b int) int {
	if a > b {
		return a
	}
	return b
}
