name: Build Alchemy Binaries

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64
        goos: [darwin, windows, linux]
        goarch: [amd64, arm64]
        tags: [plain, db]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "."
          binary_name: "alchemy"
          ldflags: "-s -w"
          build_flags: -tags ${{ matrix.tags }}
          extra_files: LICENSE README.md
          asset_name: "alchemy-${{ env.RELEASE_TAG }}-${{ matrix.goos }}-${{ matrix.goarch }}-${{ matrix.tags }}"
