name: Build Alchemy Binaries

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  alchemy:
    name: Release Alchmey Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64
        goos: [darwin, windows, linux]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - name: Get tag
        id: tag
        uses: devops-actions/action-get-tag@main
        with:
          strip_v: true
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "."
          binary_name: "alchemy"
          ldflags: "-s -w -X 'github.com/project-chip/alchemy/config.Tag=${{ steps.tag.outputs.tag }}'"
          extra_files: LICENSE README.md
          asset_name: "alchemy-${{ steps.tag.outputs.tag }}-${{ matrix.goos }}-${{ matrix.goarch }}"
  alchemy-db:
    name: Release Alchmey DB Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64
        goos: [darwin, windows, linux]
        goarch: [amd64, arm64]
        tags: [db]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - name: Get tag
        id: tag
        uses: devops-actions/action-get-tag@main
        with:
          strip_v: true
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "."
          binary_name: "alchemy-db"
          ldflags: "-s -w -X 'github.com/project-chip/alchemy/config.Tag=${{ steps.tag.outputs.tag }}'"
          build_flags: -tags ${{ matrix.tags }}
          extra_files: LICENSE README.md
          asset_name: "alchemy-db-${{ steps.tag.outputs.tag }}-${{ matrix.goos }}-${{ matrix.goarch }}"
